import Mathlib
import Genus2Lean.HyperellipticFunctionField
import Genus2Lean.AffinePoints
import Genus2Lean.PrincipalDivisors
import Genus2Lean.LPairFinrankOneOrdAtFrac
set_option linter.style.header false

noncomputable section

open Classical
open Polynomial

variable {k : Type*} [Field k] {H : HyperellipticPolynomial k}

/-!
# The non-square-fiber closed point, replacing `IsAlgClosed.exists_pow_nat_eq`

**DRAFT — not yet build-tested. Attempt #1, per project convention (prove first,
ChatGPT only if stuck).**

**Problem.** `LPairFinrankOneOrdAtFrac.lean`'s `exists_pole_of_isCoprimeAtRoots` and
`false_of_root_of_coprimeAtRoots_zero_snd`, in their non-Weierstrass branch (`H.f.eval α
≠ 0`), both call `IsAlgClosed.exists_pow_nat_eq (H.f.eval α) (n := 2) ...` to produce
`β : k` with `β² = H.f.eval α`, then build an `H.Point := Point.mk α β`. Over a general
field `k` (in particular `k = ZMod p`), `H.f.eval α` need not be a square, so no such
`β` (hence no such `H.Point`) exists. This file attempts to replace the rational
witness point with a closed point of residue degree 2 — a `HeightOneSpectrum
(CoordinateRing H)` element lying over the prime `(X - α, T² - H.f.eval α)` — that
exists unconditionally, whether or not `H.f.eval α` is a square in `k`.

**Strategy.** `L := AdjoinRoot (T^2 - C (H.f.eval α) : k[X])` is the (possibly trivial,
if `H.f.eval α` is a square — then `L ≅ k × k`; possibly a field extension of degree 2
otherwise) `k`-algebra generated by a square root `β' := root (...)` of `H.f.eval α`.
Build a ring hom `φ : CoordinateRing H →+* L` by `AdjoinRoot.lift`, sending
`x ↦ algebraMap k L α` and `y ↦ β'` (checking `β'^2 = φ(H.f)`, which holds since
`φ(H.f) = H.f.eval α` under the evaluation-at-`α` composite, by design). Then
`v.asIdeal := RingHom.ker φ` (comap'd appropriately) is a prime ideal of `CoordinateRing
H`; showing it's height-one (`≠ ⊥`, `≠ ⊤`) makes it a genuine `HeightOneSpectrum`
element, playing the role the old `Point.mk α β` played, but without needing `β ∈ k`.

**Status: `nonSquareFiberHeightOne` is fully constructed, no `sorry`s**, and so is the
`ordAtSpec`-flavored membership lemma (`toPair_mem_nonSquareFiberIdeal_iff`) needed to
actually compute with this point. The ring hom, its surjectivity onto `SqrtExt
(H.f.eval α)`, maximality of its kernel, `≠ ⊥` (via `Ring.ne_bot_of_isMaximal_of_
not_isField`, same as the rational-point case), and the membership characterization
are all proved below. What's still open — flagged in the closing remark at the end of
this file — is rewiring `LPairFinrankOneOrdAtFrac.lean`'s
`false_of_root_of_coprimeAtRoots_zero_snd` to actually use these instead of
`IsAlgClosed.exists_pow_nat_eq`. -/

namespace HyperellipticPolynomial

/-- The quadratic `k`-algebra `k[T]/(T² - c)` for `c : k`, used as the target of the
evaluation-at-`α` ring hom below. When `c` is a nonzero non-square this is a genuine
degree-2 field extension of `k`; when `c` is a square it's isomorphic to `k × k`;
either way it's a well-defined commutative ring containing a square root of `c`.

Declared as an `abbrev` (reducible type synonym for `AdjoinRoot (X^2 - C c)`), not a
`def`, so that instances found for `AdjoinRoot (X^2 - C c)` — in particular a later
local `Field` instance gated on `[Fact (Irreducible _)]` — unify with `SqrtExt c`
on the nose instead of creating a diamond against separately-declared `CommRing`/
`Algebra` instances. -/
abbrev SqrtExt (c : k) : Type _ := AdjoinRoot (X ^ 2 - C c : k[X])

/-- The chosen square root of `c` living in `SqrtExt c`. -/
def sqrtExtRoot (c : k) : SqrtExt c := AdjoinRoot.root (X ^ 2 - C c)

theorem sqrtExtRoot_sq (c : k) :
    sqrtExtRoot c ^ 2 = algebraMap k (SqrtExt c) c := by
  have h := AdjoinRoot.eval₂_root (X ^ 2 - C c : k[X])
  rw [eval₂_sub, eval₂_pow, eval₂_X, eval₂_C] at h
  exact sub_eq_zero.mp h

/-- **The ring hom `CoordinateRing H →+* SqrtExt (H.f.eval α)`, sending `x ↦ α`,
`y ↦ sqrtExtRoot (H.f.eval α)`.** Built via `AdjoinRoot.lift` on `CoordinateRing H =
AdjoinRoot (X² - C H.f : k[X])` — note the *base ring* of this `AdjoinRoot` is `k[X]`,
not `k` (matching `HyperellipticFunctionField.lean`'s `CoordinateRing`/`evalAtPoint`
convention), so the ring hom fed to `lift` is `k[X] →+* SqrtExt (H.f.eval α)`, namely
`(algebraMap k _).comp (evalRingHom α)`, discharging the side condition
`eval₂ i (sqrtExtRoot c) (X^2 - C H.f) = 0` the same way `evalAtPoint`/`y_sq_eq` do:
unfold `eval₂` over `sub`/`pow`/`X`/`C`, then close with `sqrtExtRoot_sq`. -/
def evalAtNonSquareFiber (α : k) :
    CoordinateRing H →+* SqrtExt (H.f.eval α) :=
  AdjoinRoot.lift
    ((algebraMap k (SqrtExt (H.f.eval α))).comp (Polynomial.evalRingHom α))
    (sqrtExtRoot (H.f.eval α))
    (by
      rw [eval₂_sub, eval₂_pow, eval₂_X, eval₂_C, sqrtExtRoot_sq, sub_eq_zero]
      rfl)

/-- **Gap 1 (ChatGPT-assisted, consultation transcript kept close to verbatim).**
`X² - C c` is irreducible over `k` when `c` is a non-square: degree `2` (∈ `[1,3]`),
no root in `k` (a root `x` would give `x² = c`, i.e. `IsSquare c`, contradicting
`hns`), so `Polynomial.irreducible_of_degree_le_three_of_not_isRoot` applies directly
— no need to separately handle the monic/roots-multiset route. -/
theorem irreducible_X_sq_sub_C (c : k) (hns : ¬ IsSquare c) :
    Irreducible (X ^ 2 - C c : k[X]) := by
  apply Polynomial.irreducible_of_degree_le_three_of_not_isRoot
  · -- `natDegree (X^2 - C c) = 2 ∈ Finset.Icc 1 3`.
    have hnd : (X ^ 2 - C c : k[X]).natDegree = 2 := by compute_degree!
    rw [hnd]; decide
  · intro x hx
    apply hns
    have hx2 : x ^ 2 = c := by
      have h := hx
      unfold Polynomial.IsRoot at h
      simp only [eval_sub, eval_pow, eval_X, eval_C] at h
      exact sub_eq_zero.mp h
    exact ⟨x, by rw [← hx2]; ring⟩

/-- **Gap 2.** `SqrtExt c` is a field when `c` is a non-square, via `AdjoinRoot.
instField`'s `[Fact (Irreducible _)]` instance, fed `irreducible_X_sq_sub_C`. The
`Fact` wrapper is introduced explicitly via `haveI` — a bare `Irreducible` term in
context does not get picked up automatically. `SqrtExt` is an `abbrev` for
`AdjoinRoot _` (see above), so this `Field` instance and the ambient `IsField (SqrtExt
c)` goal both resolve through the same underlying `Semiring` path — no diamond. -/
theorem sqrtExt_isField (c : k) (hns : ¬ IsSquare c) : IsField (SqrtExt c) := by
  haveI : Fact (Irreducible (X ^ 2 - C c : k[X])) := ⟨irreducible_X_sq_sub_C c hns⟩
  exact Field.toIsField (SqrtExt c)

/-- The candidate prime ideal: kernel of `evalAtNonSquareFiber α`. -/
def nonSquareFiberIdeal (α : k) : Ideal (CoordinateRing H) :=
  RingHom.ker (evalAtNonSquareFiber (H := H) α)

/-- `evalAtNonSquareFiber α` is surjective onto `SqrtExt (H.f.eval α)`: its range is a
`k`-subalgebra containing both `k` (via the base ring hom) and `sqrtExtRoot (H.f.eval
α)` (the image of `y`, via `AdjoinRoot.lift_root`), hence contains
`Algebra.adjoin k {sqrtExtRoot (H.f.eval α)}`, which is all of `SqrtExt (H.f.eval α)`
by `AdjoinRoot.adjoinRoot_eq_top`. -/
theorem evalAtNonSquareFiber_surjective (α : k) :
    Function.Surjective (evalAtNonSquareFiber (H := H) α) := by
  set c := H.f.eval α with hc_def
  have hroot_mem : sqrtExtRoot c ∈ Set.range (evalAtNonSquareFiber (H := H) α) :=
    ⟨y H, AdjoinRoot.lift_root _⟩
  have hbase_mem : ∀ a : k,
      algebraMap k (SqrtExt c) a ∈ Set.range (evalAtNonSquareFiber (H := H) α) := by
    intro a
    refine ⟨algebraMap k[X] (CoordinateRing H) (C a), ?_⟩
    change
      (AdjoinRoot.lift
        ((algebraMap k (SqrtExt c)).comp (Polynomial.evalRingHom α))
        (sqrtExtRoot c) _)
        (AdjoinRoot.of (X ^ 2 - C H.f) (C a))
      = algebraMap k (SqrtExt c) a
    rw [AdjoinRoot.lift_of]
    simp [RingHom.comp_apply, Polynomial.evalRingHom]
  -- Assemble: package the range of `evalAtNonSquareFiber α` as a `Subalgebra k
  -- (SqrtExt c)` — it's closed under `+`, `*`, contains `0, 1`, and contains
  -- `algebraMap k _ a` for every `a` (`hbase_mem`), so it genuinely is a
  -- `k`-subalgebra, not just a subring.
  set S : Subalgebra k (SqrtExt c) :=
    { carrier := Set.range (evalAtNonSquareFiber (H := H) α)
      mul_mem' := by
        rintro _ _ ⟨p, rfl⟩ ⟨q, rfl⟩
        exact ⟨p * q, map_mul (evalAtNonSquareFiber (H := H) α) p q⟩
      add_mem' := by
        rintro _ _ ⟨p, rfl⟩ ⟨q, rfl⟩
        exact ⟨p + q, map_add (evalAtNonSquareFiber (H := H) α) p q⟩
      algebraMap_mem' := hbase_mem } with hS_def
  have hSroot : sqrtExtRoot c ∈ S := hroot_mem
  have hadjoin_le : Algebra.adjoin k ({sqrtExtRoot c} : Set (SqrtExt c)) ≤ S :=
    Algebra.adjoin_le (by simpa using hSroot)
  have htop : Algebra.adjoin k ({sqrtExtRoot c} : Set (SqrtExt c)) = ⊤ := by
    -- `sqrtExtRoot c = AdjoinRoot.root (X^2 - C c)` by `sqrtExtRoot`'s definition, so
    -- this is a direct instantiation of `AdjoinRoot.adjoinRoot_eq_top`.
    unfold sqrtExtRoot
    exact AdjoinRoot.adjoinRoot_eq_top
  rw [htop] at hadjoin_le
  intro s
  exact hadjoin_le (Algebra.mem_top)

/-- **`nonSquareFiberIdeal α` is maximal.** Kernel of a surjective ring hom onto the
field `SqrtExt (H.f.eval α)`, so `RingHom.ker_isMaximal_of_surjective` applies — same
lemma `pointIdeal_isMaximal` uses for rational points. -/
theorem nonSquareFiberIdeal_isMaximal (α : k) (hns : ¬ IsSquare (H.f.eval α)) :
    (nonSquareFiberIdeal (H := H) α).IsMaximal := by
  haveI : Fact (Irreducible (X ^ 2 - C (H.f.eval α) : k[X])) :=
    ⟨irreducible_X_sq_sub_C (H.f.eval α) hns⟩
  exact RingHom.ker_isMaximal_of_surjective (evalAtNonSquareFiber (H := H) α)
    (evalAtNonSquareFiber_surjective (H := H) α)

/-- **`nonSquareFiberIdeal α ≠ ⊥`.** Needed for the height-one condition. Same shape
as `pointIdeal_ne_bot` (`CoordinateRing H` is not a field, `Ring.
ne_bot_of_isMaximal_of_not_isField` applies once maximality is known). -/
theorem nonSquareFiberIdeal_ne_bot (α : k) (hns : ¬ IsSquare (H.f.eval α)) :
    (nonSquareFiberIdeal (H := H) α) ≠ ⊥ :=
  Ring.ne_bot_of_isMaximal_of_not_isField
    (nonSquareFiberIdeal_isMaximal (H := H) α hns) coordinateRing_not_isField

/-! ## The `ordAtSpec`-flavored membership lemma, for use at non-square fibers

`false_of_root_of_coprimeAtRoots_zero_snd`'s (`LPairFinrankOneOrdAtFrac.lean`)
unramified branch computes `ordAt Q a b`/`ordAt Q c 0` via `toPair_mem_pointIdeal_iff`
(`LCanonicalElementary.lean`) — membership of `toPair H A B` in the *rational* point
ideal `pointIdeal Q`, characterized by evaluation: `A.eval Q.X + B.eval Q.X * Q.Y = 0`.
The two lemmas below are the exact analogue for `nonSquareFiberIdeal`, following
`evalAtPoint_toPair`/`toPair_mem_pointIdeal_iff`'s proof shape line for line — unfold
`toPair` into its `algebraMap _ A + algebraMap _ B * y H` shape, push
`evalAtNonSquareFiber α` through `map_add`/`map_mul`, evaluate each piece via the same
computations already proved for `evalAtNonSquareFiber_surjective` above
(`algebraMap k[X] (CoordinateRing H) (C a) ↦ algebraMap k (SqrtExt c) a` and
`y H ↦ sqrtExtRoot c`), then read off ideal membership via `RingHom.mem_ker`. -/

/-- `evalAtNonSquareFiber α` applied to `toPair H A B`, computed in closed form:
`A.eval α`'s and `B.eval α`'s images under `algebraMap k (SqrtExt (H.f.eval α))`,
combined the same way `toPair H A B` itself combines `A`, `B`, `y H`. -/
theorem evalAtNonSquareFiber_toPair (α : k) (A B : k[X]) :
    evalAtNonSquareFiber (H := H) α (toPair H A B) =
      algebraMap k (SqrtExt (H.f.eval α)) (A.eval α) +
        algebraMap k (SqrtExt (H.f.eval α)) (B.eval α) * sqrtExtRoot (H.f.eval α) := by
  set c := H.f.eval α with hc_def
  have hA : evalAtNonSquareFiber (H := H) α (algebraMap k[X] (CoordinateRing H) A) =
      algebraMap k (SqrtExt c) (A.eval α) := by
    change
      (AdjoinRoot.lift
        ((algebraMap k (SqrtExt c)).comp (Polynomial.evalRingHom α))
        (sqrtExtRoot c) _)
        (AdjoinRoot.of (X ^ 2 - C H.f) A)
      = algebraMap k (SqrtExt c) (A.eval α)
    rw [AdjoinRoot.lift_of]
    simp [RingHom.comp_apply, Polynomial.evalRingHom]
  have hB : evalAtNonSquareFiber (H := H) α (algebraMap k[X] (CoordinateRing H) B) =
      algebraMap k (SqrtExt c) (B.eval α) := by
    change
      (AdjoinRoot.lift
        ((algebraMap k (SqrtExt c)).comp (Polynomial.evalRingHom α))
        (sqrtExtRoot c) _)
        (AdjoinRoot.of (X ^ 2 - C H.f) B)
      = algebraMap k (SqrtExt c) (B.eval α)
    rw [AdjoinRoot.lift_of]
    simp [RingHom.comp_apply, Polynomial.evalRingHom]
  have hy : evalAtNonSquareFiber (H := H) α (y H) = sqrtExtRoot c :=
    AdjoinRoot.lift_root _
  unfold HyperellipticPolynomial.toPair
  rw [map_add, map_mul, hA, hB, hy]

/-- **Membership characterization for `nonSquareFiberIdeal`**, the analogue of
`toPair_mem_pointIdeal_iff` for the non-square-fiber closed point: `toPair H A B ∈
nonSquareFiberIdeal α ↔` the corresponding element of `SqrtExt (H.f.eval α)` vanishes.
Immediate from `evalAtNonSquareFiber_toPair` and `nonSquareFiberIdeal α = RingHom.ker
(evalAtNonSquareFiber α)`. -/
theorem toPair_mem_nonSquareFiberIdeal_iff (α : k) (A B : k[X]) :
    toPair H A B ∈ nonSquareFiberIdeal (H := H) α ↔
      algebraMap k (SqrtExt (H.f.eval α)) (A.eval α) +
        algebraMap k (SqrtExt (H.f.eval α)) (B.eval α) * sqrtExtRoot (H.f.eval α) = 0 := by
  rw [nonSquareFiberIdeal, RingHom.mem_ker, evalAtNonSquareFiber_toPair]

/-- **The non-square-fiber closed point itself**, as a `HeightOneSpectrum` element.
This is the intended replacement for `Point.mk α β` in
`exists_pole_of_isCoprimeAtRoots`'s non-Weierstrass branch, usable when `H.f.eval α`
is a non-square (the case `IsAlgClosed.exists_pow_nat_eq` can't handle over general
`k`). -/
def nonSquareFiberHeightOne [IsDedekindDomain (CoordinateRing H)]
    (α : k) (hns : ¬ IsSquare (H.f.eval α)) :
    IsDedekindDomain.HeightOneSpectrum (CoordinateRing H) where
  asIdeal := nonSquareFiberIdeal (H := H) α
  isPrime := (nonSquareFiberIdeal_isMaximal (H := H) α hns).isPrime
  ne_bot := nonSquareFiberIdeal_ne_bot (H := H) α hns

/-! ## What's still needed after the above compiles

`false_of_root_of_coprimeAtRoots_zero_snd`'s (`LPairFinrankOneOrdAtFrac.lean`)
unramified branch needs rewiring to case-split on `IsSquare (H.f.eval α)`: the square
case keeps its existing `Point.mk α β`/`ordAt`-based argument; the non-square case
swaps in `nonSquareFiberHeightOne α hns` together with `toPair_mem_nonSquareFiberIdeal_
iff` above in place of `toPair_mem_pointIdeal_iff`, and an `ordAtSpec`-level order-of-
vanishing computation (the `nonSquareFiberIdeal` analogue of `ordAt_eq_rootMultiplicity_
unramified`) in place of `ordAt_eq_rootMultiplicity_unramified` — not yet attempted. -/

end HyperellipticPolynomial
