#!/usr/bin/env julia

using Oscar

################################################################################
#
#  elim3.jl  --  Symmetric-invariant reformulation of elim2.jl.
#
#  elim2.jl confirmed (check_swap_symmetry) that u_RS/v_RS for both samples
#  are invariant under the SIMULTANEOUS swap (a1,wa1)<->(a2,wa2) [and
#  (b1,wb1)<->(b2,wb2)]. The naive next step -- substitute s1=a1+a2,
#  s2=a1*a2 and "likewise for b", dropping the w's in as-is -- is WRONG:
#  it assumes the invariant ring of this Z/2 action is generated by
#  {s1,s2,sigma,pi} (sigma=wa1+wa2, pi=wa1*wa2), but it is not. That
#  4-generator set misses a genuinely independent invariant:
#
#      delta_a := (a1-a2)*(wa1-wa2)  =  a1*wa1 + a2*wa2 - a1*wa2 - a2*wa1
#
#  which is fixed by the simultaneous swap but is NOT a polynomial in
#  s1,s2,sigma,pi alone (it changes sign under swapping ONLY the a's or
#  ONLY the w's, which s1,s2,sigma,pi can't detect). Verified by hand +
#  sympy on a toy Cramer's-rule construction structurally analogous to
#  this codebase's phi-construction (see /home/claude/symcheck/*.py) --
#  a swap-invariant rational function built from individual wa1,wa2
#  divided by (a1-a2) does NOT reduce to F(s1,s2,sigma,pi) alone; it
#  needs delta as a genuinely separate coordinate, related to the other
#  four by exactly one relation:
#
#      delta_a^2 = (s1^2 - 4*s2) * (sigma^2 - 4*pi)
#
#  The full invariant ring for sample 1 is generated by
#  {s1, s2, sigma, pi, delta_a}, i.e. THREE effective new variables
#  replacing the four raw (a1,a2,wa1,wa2) once the curve relations
#  (which pin down pi and constrain sigma) are imposed -- not a
#  2-variable collapse, but real all the same, since it quotients out
#  the Z/2 x Z/2 symmetry (sample-1 swap x sample-2 swap) the raw
#  8-variable ring was blind to.
#
#  This script does NOT assume u_RS/v_RS reduce cleanly into this new
#  ring -- it PERFORMS the substitution and reports the resulting
#  degrees/term-counts directly against elim2.jl's real tower output,
#  so we get a real yes/no rather than another round of toy-model
#  extrapolation.
#
################################################################################

const PHI_GENERAL_SRC = joinpath(@__DIR__, "phi_general", "src")
include(joinpath(PHI_GENERAL_SRC, "trial3_phi_symbolic_unified.jl"))
using .PhiSymbolic

const p = 2371157
const F_POLY_ASC = [2, 1, 0, 0, 0, 1]   # y^2 = x^5 + x + 2, ascending coeffs
F = GF(p)

const K1, c1 = 2, 2
const fixed1 = Tuple{Int,Int}[]
const u0_1, u1_1, v0_1, v1_1 = 468873, 956582, 2168176, 2288437

const K2, c2 = 3, 2
const fixed2 = [(196, 793353)]
const u0_2, u1_2, v0_2, v1_2 = 2112189, 375309, 801778, 2048138

println("Calling PhiSymbolic.symbolic_residual for sample 1 (K=$K1, c=$c1)...")
res1 = PhiSymbolic.symbolic_residual(K1, c1, fixed1, u0_1, u1_1, v0_1, v1_1, F_POLY_ASC, p)

println("Calling PhiSymbolic.symbolic_residual for sample 2 (K=$K2, c=$c2)...")
res2 = PhiSymbolic.symbolic_residual(K2, c2, fixed2, u0_2, u1_2, v0_2, v1_2, F_POLY_ASC, p)

if isempty(res1.u_RS_coeffs) || isempty(res1.v_RS_coeffs)
    error("sample 1 (K=$K1): construction failed or degenerate")
end
if isempty(res2.u_RS_coeffs) || isempty(res2.v_RS_coeffs)
    error("sample 2 (K=$K2): construction failed or degenerate")
end

################################################################################
# Step 1: build the RAW ring (same as elim2.jl) and map coefficients into it.
# We need this first because the substitution into the invariant ring below
# is done by SUBSTITUTION of raw generators -> invariant-ring expressions,
# not by re-deriving u_RS/v_RS from scratch.
################################################################################

R, (wa1, wa2, wb1, wb2, a2, a1, b2, b1) = polynomial_ring(
    F, ["wa1", "wa2", "wb1", "wb2", "a2", "a1", "b2", "b1"]
)

function _reduce_frac(num, den)
    iszero(num) && return (num, one(den))
    g = gcd(num, den)
    if !isone(g)
        num = divexact(num, g)
        den = divexact(den, g)
    end
    return (num, den)
end

function _base_frac_to_ring(val, t_gens::Vector)
    num = numerator(val)
    den = denominator(val)
    num_R = evaluate(num, t_gens)
    den_R = evaluate(den, t_gens)
    return _reduce_frac(num_R, den_R)
end

function _tower_to_ring(val, level::Int, t_gens::Vector, w_gens::Vector)
    if level == 0
        return _base_frac_to_ring(val, t_gens)
    end
    val_poly = data(val)
    c0 = coeff(val_poly, 0)
    c1 = coeff(val_poly, 1)
    n0, d0 = _tower_to_ring(c0, level - 1, t_gens, w_gens)
    n1, d1 = _tower_to_ring(c1, level - 1, t_gens, w_gens)
    wv = w_gens[level]
    num = n0 * d1 + n1 * d0 * wv
    den = d0 * d1
    return _reduce_frac(num, den)
end

tower_to_ring(val, t_gens::Vector, w_gens::Vector) = _tower_to_ring(val, 2, t_gens, w_gens)

println("Threads.nthreads() = ", Threads.nthreads())

t_gens_1 = [a1, a2]
w_gens_1 = [wa1, wa2]
t_gens_2 = [b1, b2]
w_gens_2 = [wb1, wb2]

function map_coeffs_threaded(coeffs, t_gens, w_gens)
    n = length(coeffs)
    nums = Vector{Any}(undef, n)
    dens = Vector{Any}(undef, n)
    Threads.@threads for i in 1:n
        nums[i], dens[i] = tower_to_ring(coeffs[i], t_gens, w_gens)
    end
    return nums, dens
end

u1_num, u1_den = map_coeffs_threaded(res1.u_RS_coeffs, t_gens_1, w_gens_1)
v1_num, v1_den = map_coeffs_threaded(res1.v_RS_coeffs, t_gens_1, w_gens_1)
u2_num, u2_den = map_coeffs_threaded(res2.u_RS_coeffs, t_gens_2, w_gens_2)
v2_num, v2_den = map_coeffs_threaded(res2.v_RS_coeffs, t_gens_2, w_gens_2)

println("Mapped both samples into the raw 8-variable ring R.")
println()

################################################################################
# Step 2: build the INVARIANT ring
#
#   R_inv = F[s1, s2, sigma_a, pi_a, delta_a,  s1b, s2b, sigma_b, pi_b, delta_b]
#
# and the substitution homomorphism R -> Frac(R_inv) is NOT a ring map in
# the naive sense -- (a1,a2) individually are only defined up to the Z/2
# swap once we're in invariant-land, so there is no single polynomial
# a1 = phi(s1,s2,delta_a,...) to substitute. Instead we use the standard
# trick for expressing a swap-ANTIinvariant quantity (needed to recover
# a1,a2 individually as ROOTS) via the resolvent:
#
#   a1, a2 are the two roots of   T^2 - s1*T + s2 = 0     (over R_inv)
#   wa1,wa2 are the two roots of  T^2 - sigma*T + pi = 0  (over R_inv)
#
# paired according to delta_a = (a1-a2)*(wa1-wa2) (this is what pins down
# WHICH root of the a-resolvent goes with WHICH root of the w-resolvent --
# exactly the pairing information the naive 4-generator ring couldn't see).
#
# Rather than solving a quadratic explicitly (introducing yet another
# square root into the ring), we substitute directly using:
#
#   a1 - a2  =: Da        satisfies Da^2 = s1^2 - 4*s2
#   wa1 - wa2 =: Dw        satisfies Dw^2 = sigma^2 - 4*pi
#   Da*Dw = delta_a                              (definition/relation)
#
#   a1 = (s1 + Da)/2,  a2 = (s1 - Da)/2
#   wa1 = (sigma + Dw)/2,  wa2 = (sigma - Dw)/2
#
# and Dw is eliminated in favor of delta_a/Da (since Dw = delta_a/Da,
# whenever Da != 0 -- i.e. a1 != a2, which holds generically/off a
# measure-zero locus we don't care about for a discrete-log search).
#
# So: introduce Da as ONE more ring variable (satisfying Da^2=s1^2-4*s2),
# and express everything else via Da, s1, s2, sigma, pi, delta_a -- i.e.
# the ring is
#
#   F[s1,s2,sigma,pi,delta_a,Da]/(Da^2 - (s1^2-4*s2))
#
# a degree-2 extension of the 5-generator invariant ring by Da (same
# role as adjoining a single square root, standard for resolving a
# 2-element Galois-type quotient back into individual roots when needed).
# This keeps everything POLYNOMIAL (no explicit sqrt/division-introduced
# denominators beyond the /2, which is a unit since p is odd).
################################################################################

R_inv, inv_gens = polynomial_ring(
    F,
    ["s1", "s2", "sigma_a", "pi_a", "delta_a", "Da",
     "s1b", "s2b", "sigma_b", "pi_b", "delta_b", "Db"]
)
s1_v, s2_v, sigma_a_v, pi_a_v, delta_a_v, Da_v,
    s1b_v, s2b_v, sigma_b_v, pi_b_v, delta_b_v, Db_v = inv_gens

const TWO_INV = inv(F(2))

# a1,a2 from s1,Da ; wa1,wa2 from sigma_a, Dw=delta_a/Da
# NOTE: this substitution is only valid where Da != 0 (a1 != a2). Since
# a1,a2 are meant to be two DISTINCT symbolic anchors by construction
# (the whole point of c=2 free anchors), this is the generic/intended
# case, not a degenerate edge case being swept under the rug.
a1_sub_num = s1_v + Da_v          # a1 = (s1+Da)/2  -- numerator over implicit /2
a2_sub_num = s1_v - Da_v          # a2 = (s1-Da)/2

# wa1 = (sigma_a + delta_a/Da)/2 = (sigma_a*Da + delta_a) / (2*Da)
# wa2 = (sigma_a - delta_a/Da)/2 = (sigma_a*Da - delta_a) / (2*Da)
wa1_sub_num = sigma_a_v * Da_v + delta_a_v   # over implicit /(2*Da)
wa2_sub_num = sigma_a_v * Da_v - delta_a_v

b1_sub_num = s1b_v + Db_v
b2_sub_num = s1b_v - Db_v
wb1_sub_num = sigma_b_v * Db_v + delta_b_v
wb2_sub_num = sigma_b_v * Db_v - delta_b_v

# Since a1,wa1,a2,wa2,b1,wb1,b2,wb2 all appear with denominators (2 or
# 2*Da / 2*Db) once substituted, and u1_num/u1_den etc. are RATIOS
# (num/den) built purely from polynomial operations (mult, add, no
# division except the outer num/den split already tracked separately),
# the cleanest approach is: substitute into num and den SEPARATELY, then
# work in Frac(R_inv) using AbstractAlgebra's fraction_field, which DOES
# support division cleanly, then extract numerator/denominator at the
# very end via numerator()/denominator().
FR_inv = fraction_field(R_inv)

a1_sub = FR_inv(a1_sub_num) * TWO_INV
a2_sub = FR_inv(a2_sub_num) * TWO_INV
wa1_sub = FR_inv(wa1_sub_num) * TWO_INV * inv(FR_inv(Da_v))
wa2_sub = FR_inv(wa2_sub_num) * TWO_INV * inv(FR_inv(Da_v))

b1_sub = FR_inv(b1_sub_num) * TWO_INV
b2_sub = FR_inv(b2_sub_num) * TWO_INV
wb1_sub = FR_inv(wb1_sub_num) * TWO_INV * inv(FR_inv(Db_v))
wb2_sub = FR_inv(wb2_sub_num) * TWO_INV * inv(FR_inv(Db_v))

subst_map = Dict(
    wa1 => wa1_sub, wa2 => wa2_sub, a1 => a1_sub, a2 => a2_sub,
    wb1 => wb1_sub, wb2 => wb2_sub, b1 => b1_sub, b2 => b2_sub,
)

# Evaluate a raw-ring polynomial (element of R) at the substitution map,
# landing in FR_inv = Frac(R_inv).
function substitute_into_invariant_ring(f)
    return evaluate(f, [subst_map[g] for g in gens(R)])
end

println("===========================================================")
println("Substituting u_RS/v_RS numerators+denominators into the")
println("invariant ring via (a1,a2,wa1,wa2) -> (s1,Da,sigma_a,delta_a)")
println("[and likewise for b]. This is the REAL test -- reporting")
println("actual resulting degree/term counts, not a toy estimate.")
println("===========================================================")
println()

function report_substitution(label, nums, dens)
    for (i, (n, d)) in enumerate(zip(nums, dens))
        n_sub = substitute_into_invariant_ring(n)
        d_sub = substitute_into_invariant_ring(d)
        # n_sub, d_sub are elements of FR_inv; get their own num/den in R_inv
        nn = numerator(n_sub)
        nd = denominator(n_sub)
        dn = numerator(d_sub)
        dd = denominator(d_sub)
        println("  $label[$i]:")
        println("     num_sub: as-fraction numerator degree=", total_degree(nn),
                " terms=", length(terms(nn)), "   denom degree=", total_degree(nd),
                " terms=", length(terms(nd)))
        println("     den_sub: as-fraction numerator degree=", total_degree(dn),
                " terms=", length(terms(dn)), "   denom degree=", total_degree(dd),
                " terms=", length(terms(dd)))
    end
end

println("-- u1 (sample 1, u_RS) --")
report_substitution("u1", u1_num, u1_den)
println()
println("-- v1 (sample 1, v_RS) --")
report_substitution("v1", v1_num, v1_den)
println()
println("-- u2 (sample 2, u_RS) --")
report_substitution("u2", u2_num, u2_den)
println()
println("-- v2 (sample 2, v_RS) --")
report_substitution("v2", v2_num, v2_den)
println()

println("===========================================================")
println("If the degree/term counts above are NOT dramatically smaller")
println("than elim2.jl's raw per-sample sizes (deg 16-24, ~81-529")
println("terms), OR if they show heavy denominators dominated by high")
println("powers of Da/Db (meaning the substitution just relocated the")
println("complexity rather than removing it), the symmetric-invariant")
println("reformulation is NOT the win the handoff assumed and should")
println("be abandoned in favor of a different lever.")
println("===========================================================")

################################################################################
# Step 3: build the ideal in R_inv and actually try groebner_basis.
#
# Generators of the ideal, in R_inv (plain polynomial ring, NOT the
# fraction field -- clear denominators from the substituted num_sub/
# den_sub pairs first):
#
#   - coeff_equal(num1_sub, den1_sub, num2_sub, den2_sub) for each
#     matched u_RS/v_RS coefficient, exactly as elim2.jl's Fu/Fv, but
#     now built from the substituted (invariant-ring) fractions instead
#     of the raw ring's.
#   - curve-derived relations that pin down pi_a, sigma_a (and pi_b,
#     sigma_b): pi_a^2 = f(a1)*f(a2) as a poly in s1,s2 (Vieta-resultant),
#     sigma_a^2 = f(a1)+f(a2)+2*pi_a as a poly in s1,s2,pi_a.
#   - the two Da/Db resolvent relations: Da^2 - (s1^2-4*s2),
#     Db^2 - (s1b^2-4*s2b).
#   - the delta-consistency relation: delta_a^2 - (s1^2-4*s2)*(sigma_a^2-4*pi_a),
#     and likewise for b (implied by the others, but including it explicitly
#     costs little and may help F4's degree-of-regularity by giving it a
#     low-degree relation to reduce against early).
#
# Including ALL of these (not just Da^2/Db^2) is the fix flagged after the
# first run: without them, F4 wastes effort on redundant high powers of
# Da/Db/pi_a/sigma_a that are trivially reducible via relations that were
# never told to the ideal.
################################################################################

println()
println("===========================================================")
println("Building ideal in R_inv (with resolvent + curve relations)")
println("and attempting groebner_basis on the U-only system first.")
println("===========================================================")
println()

function coeff_equal_inv(num1_sub, den1_sub, num2_sub, den2_sub)
    # num1_sub etc are elements of FR_inv (Frac(R_inv)); cross-multiply
    # AS FRACTIONS, then take numerator() at the end to land back in
    # R_inv as a plain polynomial (same coeff_equal pattern as elim2.jl,
    # just deferred to the end since these are fraction-field elements
    # here, not already-cleared R elements).
    lhs = num1_sub * den2_sub
    rhs = num2_sub * den1_sub
    diff = lhs - rhs
    return numerator(diff)
end

Fu_inv = Any[]
for i in 1:2   # N_U_MATCH = 2 (matches elim2.jl: x^0,x^1 coefficients, x^2 trivial/monic skipped)
    n1 = substitute_into_invariant_ring(u1_num[i]); d1 = substitute_into_invariant_ring(u1_den[i])
    n2 = substitute_into_invariant_ring(u2_num[i]); d2 = substitute_into_invariant_ring(u2_den[i])
    push!(Fu_inv, coeff_equal_inv(n1, d1, n2, d2))
end

Fv_inv = Any[]
for i in 1:length(v1_num)
    n1 = substitute_into_invariant_ring(v1_num[i]); d1 = substitute_into_invariant_ring(v1_den[i])
    n2 = substitute_into_invariant_ring(v2_num[i]); d2 = substitute_into_invariant_ring(v2_den[i])
    push!(Fv_inv, coeff_equal_inv(n1, d1, n2, d2))
end

println("Fu_inv/Fv_inv built. Sizes:")
for (i, g) in enumerate(Fu_inv)
    println("  Fu_inv[$i]: degree=", total_degree(g), " terms=", length(terms(g)))
end
for (i, g) in enumerate(Fv_inv)
    println("  Fv_inv[$i]: degree=", total_degree(g), " terms=", length(terms(g)))
end
println()

# Curve-derived relations pinning pi_a, sigma_a (resultant of f(a1),f(a2)
# expressed via s1,s2; f(a1)+f(a2) expressed via s1,s2 through Newton's
# identities for the power sum a1^5+a2^5). Built directly by substituting
# a1=(s1+Da)/2, a2=(s1-Da)/2 into f(a1)*f(a2) and f(a1)+f(a2) and clearing
# denominators -- reuses the substitution machinery already built above
# instead of hand-deriving Vieta/Newton-identity formulas symbolically.
function f_of(x)
    return F(2) + x + x^5
end

f_a1 = f_of(a1_sub)   # FR_inv element, in terms of s1,Da
f_a2 = f_of(a2_sub)
pi_a_relation_rhs = f_a1 * f_a2          # should equal pi_a^2 once reduced
sigma_a_relation_rhs = f_a1 + f_a2

# NOTE: sigma_a^2 = (wa1+wa2)^2 = wa1^2+wa2^2+2*wa1*wa2 = f(a1)+f(a2)+2*pi_a
# so: sigma_a^2 - 2*pi_a - (f(a1)+f(a2)) = 0

f_b1 = f_of(b1_sub)
f_b2 = f_of(b2_sub)
pi_b_relation_rhs = f_b1 * f_b2
sigma_b_relation_rhs = f_b1 + f_b2

function build_relation(lhs_poly_in_Rinv, rhs_frac)
    rn = numerator(rhs_frac)
    rd = denominator(rhs_frac)
    return lhs_poly_in_Rinv * rd - rn
end

rel_pi_a    = build_relation(pi_a_v^2, FR_inv(pi_a_relation_rhs))
rel_sigma_a = build_relation(sigma_a_v^2 - F(2)*pi_a_v, FR_inv(sigma_a_relation_rhs))
rel_pi_b    = build_relation(pi_b_v^2, FR_inv(pi_b_relation_rhs))
rel_sigma_b = build_relation(sigma_b_v^2 - F(2)*pi_b_v, FR_inv(sigma_b_relation_rhs))

rel_Da = Da_v^2 - (s1_v^2 - F(4)*s2_v)
rel_Db = Db_v^2 - (s1b_v^2 - F(4)*s2b_v)

rel_delta_a = delta_a_v^2 - (s1_v^2 - F(4)*s2_v) * (sigma_a_v^2 - F(4)*pi_a_v)
rel_delta_b = delta_b_v^2 - (s1b_v^2 - F(4)*s2b_v) * (sigma_b_v^2 - F(4)*pi_b_v)

RELATIONS = [rel_pi_a, rel_sigma_a, rel_pi_b, rel_sigma_b,
             rel_Da, rel_Db, rel_delta_a, rel_delta_b]

println("Structural relations built:")
for (label, r) in zip(
        ["rel_pi_a","rel_sigma_a","rel_pi_b","rel_sigma_b",
         "rel_Da","rel_Db","rel_delta_a","rel_delta_b"], RELATIONS)
    println("  $label: degree=", total_degree(r), " terms=", length(terms(r)))
end
println()

Iu_inv = ideal(R_inv, vcat(Fu_inv, RELATIONS))

block_ordering_inv = degrevlex(inv_gens[1:6]) * degrevlex(inv_gens[7:12])

println("Attempting groebner_basis(Iu_inv) [U-only system, invariant ring]...")
println("(NOTE: this may OOM or run long, same as elim2.jl's decoupled")
println("U-system did. Running U-only FIRST, before UV, on purpose --")
println("if this alone doesn't terminate in reasonable memory/time, UV")
println("(strictly bigger) won't either, and there's no point queueing it.)")
println()

GBu_inv = try
    result = groebner_basis(Iu_inv; ordering = block_ordering_inv, algorithm = :f4)
    println("(computed via algorithm = :f4)")
    result
catch e
    println("algorithm=:f4 failed (", e, "), falling back to :buchberger...")
    groebner_basis(Iu_inv; ordering = block_ordering_inv, algorithm = :buchberger)
end

println("Invariant-ring GBu has ", length(GBu_inv), " elements.")
println()
for (i, g) in enumerate(GBu_inv)
    println("--------------------------------------------------")
    println("g", i, ": degree=", total_degree(g), " terms=", length(terms(g)))
    println("--------------------------------------------------")
end

println()
println("===========================================================")
println("If this succeeded where elim2.jl's decoupled Iu OOM'd, the")
println("invariant-ring reformulation IS a real win despite the larger")
println("individual generator sizes reported in Step 2 above -- degree")
println("of regularity, not generator size, is what determines F4 cost.")
println("If this ALSO OOMs, both the raw-ring and invariant-ring")
println("formulations of this cross-K matching problem are intractable")
println("with F4 as currently applied, and it's time to reconsider the")
println("overall approach rather than trying a third ring.")
println("===========================================================")
