# =============================================================================
#  lp1_conj_deep_diag_d35.jl
#
#  D35 — Closure difference-process concentration (Δα/Δβ vs ΔP proxy).
#
#  GPT's hypothesis, restated: a closure cancels the matching LP1-conj terms
#  and leaves
#       atom(fb[i0]) - atom(fb[prev_col])  =  Δα·G + Δβ·T
#  i.e. every closure is a coincidence between two *difference* processes —
#  RHS: Δα = combined_al, generated by sums of a finite increment table
#  (so may have high additive energy / small effective support even though
#  no single α ever repeats); LHS: P - P', generated by the FB-biased walk
#  (proxied here by Δpx, the x-coordinate difference of the two FB anchors,
#  consistent with every other px-based proxy elsewhere in this file).
#
#  PRIMARY TEST — empirical range vs Uniform(0, ambient) order-statistic null.
#  At realistic closure counts (hundreds, not the tens-of-thousands a
#  collision-counting test needs against a billion-scale ambient space), the
#  question "is the support narrower than the ambient size" has to be
#  answered from the *spread* of the observed values, not from how often
#  they repeat — with n draws from a huge ambient space, near-zero repeats
#  is the EXPECTED outcome under the uniform null itself, so "no collisions"
#  is not evidence of concentration. But the range (max-min) of n iid
#  Uniform(0,N) draws is a tight, well-characterized statistic even for
#  n in the low hundreds:
#       E[range] = N(n-1)/(n+1)
#       Var[range] = N² · 2(n-1) / ((n+1)²(n+2))
#  so an observed range several std-devs below E[range] is a real,
#  statistically calibrated signal that the true support is narrower than
#  the ambient space — even with zero observed repeats. This is the test
#  that actually answers "is there a small range these are drawn from."
#
#  SECONDARY (collision-based) stats — Rényi-2 effective support, Gini,
#  Hill exponent, top-share — are still reported for completeness and
#  become informative once closure counts grow large enough for repeats to
#  occur at meaningful rates, but are explicitly NOT used to drive the
#  verdict at typical sample sizes; at n with zero collisions they are
#  mechanically uninformative (S_eff == n, Gini == 0, top-share == 1/n
#  regardless of whether the underlying support is wide or narrow) and
#  Hill's tail-index estimator is undefined on an all-singleton frequency
#  profile (would otherwise print nonsense like a Hill exponent of 1e34).
#
#  Δβ caveat: if β-tracking is disabled for this run (beta_zero=true in the
#  walker), combined_be is identically 0 for every closure by construction.
#  That shows up as "S_eff=1, top-share=1.0" — degenerate, not concentrated
#  — so the report detects the single-distinct-value case and labels it
#  explicitly instead of feeding it into the verdict as a finding.
#
#  Included by lp1_conj_deep_diag.jl; do not include directly.
# =============================================================================

# ---------------------------------------------------------------------------
#  _renyi2_support — exact Rényi-2 effective support size from a value
#  vector: S_eff = 1 / Σ_x p(x)²  where p(x) = count(x)/n.
#  Returns (S_eff, counts_dict, sorted_desc_counts).
#  S_eff == 1.0 for a single repeated value, S_eff == n for n all-distinct
#  values (the "fully uniform, no collisions observed" case).
# ---------------------------------------------------------------------------
function _renyi2_support(vals::Vector{Int})
    n = length(vals)
    n == 0 && return (NaN, Dict{Int,Int}(), Int[])

    counts = Dict{Int,Int}()
    @inbounds for v in vals
        counts[v] = get(counts, v, 0) + 1
    end

    sum_p2 = 0.0
    nf = Float64(n)
    for (_, c) in counts
        p = c / nf
        sum_p2 += p * p
    end
    s_eff = sum_p2 > 0 ? 1.0 / sum_p2 : NaN

    sorted_desc = sort(collect(values(counts)), rev=true)
    return (s_eff, counts, sorted_desc)
end

# ---------------------------------------------------------------------------
#  _range_test — the actual "is this drawn from a narrower range" test.
#
#  Compares the observed range (max-min) of n values against the order-
#  statistic null for n iid Uniform(0, ambient) draws:
#       E[range]   = N(n-1)/(n+1)
#       Var[range] = N² · 2(n-1) / ((n+1)²(n+2))
#  z = (E[range] - observed_range) / std[range]
#  z >> 0  → observed range is many std-devs NARROWER than a uniform draw
#            would produce — real evidence of a confined support.
#  z ≈ 0   → consistent with uniform.
#  z << 0  → observed range is WIDER than uniform predicts (should not
#            happen for a bounded domain; flags a units/wraparound bug if
#            it does).
#
#  Returns a NamedTuple, or nothing if n==0 or ambient<=0.
# ---------------------------------------------------------------------------
function _range_test(vals::Vector{Int}, ambient::Int)
    n = length(vals)
    (n == 0 || ambient <= 0) && return nothing

    lo, hi = extrema(vals)
    obs_range = Float64(hi - lo)
    nf = Float64(n)
    Nf = Float64(ambient)

    exp_range = Nf * (nf - 1.0) / (nf + 1.0)
    var_range = Nf^2 * 2.0 * (nf - 1.0) / ((nf + 1.0)^2 * (nf + 2.0))
    std_range = sqrt(max(var_range, 0.0))
    z = std_range > 0 ? (exp_range - obs_range) / std_range : NaN

    return (lo=lo, hi=hi, obs_range=obs_range, exp_range=exp_range,
            std_range=std_range, z=z, frac_of_ambient=obs_range / Nf)
end

# ---------------------------------------------------------------------------
#  _report_d35 — print the closure difference-process concentration report.
#
#  Arguments:
#    deep_stat — merged ConjDeepStat
#    p         — field characteristic (ambient size for the ΔP proxy side;
#                0 → skip ΔP analysis, Δα analysis still runs)
#    ell       — group order ℓ (ambient size for the Δα/Δβ side; 0 → skip)
# ---------------------------------------------------------------------------
function _report_d35(deep_stat::ConjDeepStat; p::Int = 0, ell::Int = 0)

    @printf("\n─── D35: closure difference-process concentration (Δα vs ΔP) ────────\n")

    n = length(deep_stat.d35_dalpha)
    @printf("  Closures recorded (capped at %d) : %d\n", D35_MAX_CLOSURES, n)
    @printf("  Closures seen (uncapped total)   : %d\n", deep_stat.d35_n_closures)

    if n < 4
        @printf("  (too few closures for D35 — skipping)\n\n")
        flush(stdout)
        return nothing
    end

    dalpha = deep_stat.d35_dalpha
    dbeta  = deep_stat.d35_dbeta

    # Δpx / Δpy computed here (not at record time) since p is only known
    # at report time. mod() handles negative raw differences correctly.
    have_p = p > 0
    dpx = have_p ? [mod(deep_stat.d35_px_close[i] - deep_stat.d35_px_store[i], p) for i in 1:n] : Int[]
    dpy = have_p ? [mod(deep_stat.d35_py_close[i] - deep_stat.d35_py_store[i], p) for i in 1:n] : Int[]

    n_distinct_b = length(Set(dbeta))
    beta_degenerate = n_distinct_b <= 1

    # -----------------------------------------------------------------------
    #  PRIMARY TEST — empirical range vs Uniform(0,ambient) order-statistic
    #  null. This is the test that actually answers "is there a small range
    #  these are drawn from", and it has real power even with zero observed
    #  repeats (see header docstring). Collision-based stats below are
    #  secondary and explicitly NOT used to drive the verdict.
    # -----------------------------------------------------------------------
    rt_a  = ell > 0 ? _range_test(dalpha, ell) : nothing
    rt_b  = (ell > 0 && !beta_degenerate) ? _range_test(dbeta, ell) : nothing
    rt_px = have_p ? _range_test(dpx, p) : nothing

    @printf("\n")
    @printf("  PRIMARY TEST — observed range vs Uniform(0,ambient) null (n=%d draws):\n", n)
    @printf("  %-18s  %-12s  %-12s  %12s  %12s  %12s  %8s\n",
            "quantity", "obs lo", "obs hi", "obs width", "E[width]", "width/amb", "z (narrow)")
    @printf("  %s\n", "─"^96)

    function _range_row(label::String, rt)
        rt === nothing && (@printf("  %-18s  (skipped — ambient size unavailable)\n", label); return)
        @printf("  %-18s  %-12d  %-12d  %12.4e  %12.4e  %12.4e  %8.2f\n",
                label, rt.lo, rt.hi, rt.obs_range, rt.exp_range, rt.frac_of_ambient, rt.z)
    end

    _range_row("Δα  (combined_al)", rt_a)
    if beta_degenerate
        @printf("  %-18s  (skipped — only %d distinct value(s) across all closures;\n",
                "Δβ (combined_be)", n_distinct_b)
        @printf("  %-18s   most likely β-tracking is disabled (beta_zero=true) for this\n", "")
        @printf("  %-18s   run — this is a dead variable, NOT evidence of concentration)\n", "")
    else
        _range_row("Δβ  (combined_be)", rt_b)
    end
    have_p && _range_row("Δpx (FB anchor x)", rt_px)

    @printf("\n")
    @printf("  z interpretation: z > 3  → range significantly NARROWER than uniform\n")
    @printf("                            predicts — real evidence of a confined support.\n")
    @printf("                    |z| ≤ 3 → consistent with a uniform draw at this n.\n")
    @printf("                    z < -3 → range WIDER than uniform predicts — should not\n")
    @printf("                            happen for a bounded domain; check units/wraparound\n")
    @printf("                            if this fires.\n")

    # -----------------------------------------------------------------------
    #  Occupancy sparkline — visual confirmation of WHERE in [0,ambient) the
    #  observed values actually sit, using the same bucket/sparkline
    #  convention as D34 (_d34_sparkline is defined in
    #  lp1_conj_deep_diag_d34.jl, included earlier — same module scope).
    # -----------------------------------------------------------------------
    let OCC_BUCKETS = 60
        function _occupancy(vals::Vector{Int}, ambient::Int, label::String)
            (isempty(vals) || ambient <= 0) && return
            occ_counts = zeros(Float64, OCC_BUCKETS)
            for v in vals
                bkt = clamp((v * OCC_BUCKETS) ÷ ambient, 0, OCC_BUCKETS - 1) + 1
                occ_counts[bkt] += 1.0
            end
            occupied_bkts = collect(1:OCC_BUCKETS)
            _d34_sparkline("  $label", occ_counts, occupied_bkts, 60)
        end
        @printf("\n")
        @printf("  Occupancy across [0,ambient), %d buckets (where the mass actually sits):\n", OCC_BUCKETS)
        _occupancy(dalpha, ell, "Δα   ")
        beta_degenerate || _occupancy(dbeta, ell, "Δβ   ")
        have_p && _occupancy(dpx, p, "Δpx  ")
    end

    # -----------------------------------------------------------------------
    #  SECONDARY (collision-based) statistics — Rényi-2 effective support.
    #  CAVEAT: with n in the hundreds against an ambient space in the
    #  billions, near-zero collisions is the EXPECTED outcome under the
    #  uniform null too — so S_eff≈n, Gini≈0, top-share≈1/n here do NOT by
    #  themselves indicate a uniform (vs concentrated) underlying support.
    #  These only become informative once n is large enough for the
    #  expected collision count under the null to be non-negligible. Trust
    #  the PRIMARY range test above for the actual concentration verdict at
    #  this sample size.
    # -----------------------------------------------------------------------
    @printf("\n")
    @printf("  ┄┄ secondary (collision-based) stats below — see caveat in source ┄┄\n")
    s_eff_a,  counts_a,  sorted_a  = _renyi2_support(dalpha)
    s_eff_b,  counts_b,  sorted_b  = beta_degenerate ? (NaN, Dict{Int,Int}(), Int[]) : _renyi2_support(dbeta)
    s_eff_px, counts_px, sorted_px = have_p ? _renyi2_support(dpx) : (NaN, Dict{Int,Int}(), Int[])

    @printf("\n")
    @printf("  Rényi-2 effective support S_eff = 1/Σp(x)²  (n=%d closures):\n", n)
    @printf("  %-22s  %12s  %14s  %12s  %10s\n",
            "quantity", "S_eff", "ambient size", "S_eff/ambient", "vs n")
    @printf("  %s\n", "─"^78)

    function _row(label::String, s_eff::Float64, ambient::Int)
        if ambient > 0 && !isnan(s_eff)
            ratio = s_eff / ambient
            @printf("  %-22s  %12.2f  %14d  %12.3e  %10.3f\n",
                    label, s_eff, ambient, ratio, s_eff / n)
        elseif !isnan(s_eff)
            @printf("  %-22s  %12.2f  %14s  %12s  %10.3f\n",
                    label, s_eff, "n/a", "n/a", s_eff / n)
        else
            @printf("  %-22s  %12s\n", label, "n/a")
        end
    end

    _row("Δα  (combined_al)", s_eff_a, ell)
    beta_degenerate || _row("Δβ  (combined_be)", s_eff_b, ell)
    have_p && _row("Δpx (FB anchor x)", s_eff_px, p)

    # -----------------------------------------------------------------------
    #  Concentration shape: Gini / Hill exponent / top-share, reusing the
    #  same math helpers as D19/D33/D34 for a consistent vocabulary across
    #  the whole D-series.
    #
    #  Hill's tail-index estimator is undefined (in practice: a division by
    #  a ~1e-30 floor producing nonsense like 1e34) when every multiplicity
    #  is equal — e.g. all-singleton counts, which is the typical case at
    #  this sample size with zero collisions. We detect that and print n/a
    #  instead of garbage.
    # -----------------------------------------------------------------------
    @printf("\n")
    @printf("  Concentration shape (0=uniform Gini, low top-5%%=uniform):\n")
    @printf("  %-22s  %10s  %14s  %12s\n", "quantity", "Gini", "Hill α(k=50)", "top-5% share")
    @printf("  %s\n", "─"^64)

    function _shape_row(label::String, sorted_desc::Vector{Int})
        isempty(sorted_desc) && return
        g  = _gini(sorted_desc)
        ts = _top_share(sorted_desc, 0.05)
        has_variation = !isempty(sorted_desc) && sorted_desc[1] > (isempty(sorted_desc) ? 0 : sorted_desc[end])
        if has_variation
            h = _hill_exponent(sorted_desc; k=min(50, length(sorted_desc) - 1))
            @printf("  %-22s  %10.4f  %14.3f  %12.4f\n", label, g, h, ts)
        else
            @printf("  %-22s  %10.4f  %14s  %12.4f\n", label, g, "n/a (flat)", ts)
        end
    end

    _shape_row("Δα  (combined_al)", sorted_a)
    beta_degenerate || _shape_row("Δβ  (combined_be)", sorted_b)
    have_p && _shape_row("Δpx (FB anchor x)", sorted_px)

    # -----------------------------------------------------------------------
    #  Top-10 most frequent Δα / Δpx values, with share of closures.
    # -----------------------------------------------------------------------
    @printf("\n")
    if !isempty(sorted_a) && sorted_a[1] <= 1
        @printf("  (Top-10 tables below: every Δα/Δpx value seen exactly once at this n —\n")
        @printf("   the listed \"top 10\" is an arbitrary slice, not a frequency ranking.\n")
        @printf("   Use the occupancy sparkline / range test above instead.)\n")
    end
    @printf("\n")
    @printf("  Top-10 most frequent Δα values:\n")
    @printf("  %-20s  %10s  %10s\n", "Δα value", "count", "share")
    @printf("  %s\n", "─"^44)
    top_a = sort(collect(counts_a), by = kv -> -kv[2])
    for (val, cnt) in top_a[1:min(10, length(top_a))]
        @printf("  %-20d  %10d  %10.4f\n", val, cnt, cnt / n)
    end

    if have_p
        @printf("\n")
        @printf("  Top-10 most frequent Δpx values:\n")
        @printf("  %-20s  %10s  %10s\n", "Δpx value", "count", "share")
        @printf("  %s\n", "─"^44)
        top_px = sort(collect(counts_px), by = kv -> -kv[2])
        for (val, cnt) in top_px[1:min(10, length(top_px))]
            @printf("  %-20d  %10d  %10.4f\n", val, cnt, cnt / n)
        end
    end

    # -----------------------------------------------------------------------
    #  Co-localization test: do recurring Δα and recurring Δpx happen at the
    #  SAME closures more than independence would predict? This is the
    #  direct test of "closures occur where the two concentrated sets
    #  overlap" rather than each side being concentrated for unrelated
    #  reasons. A "recurring" value is one whose count > 1 in the observed
    #  sample (i.e. this exact Δα — or Δpx — was hit by more than one
    #  closure).
    # -----------------------------------------------------------------------
    if have_p
        recur_a  = [counts_a[dalpha[i]]  > 1 for i in 1:n]
        recur_px = [counts_px[dpx[i]]    > 1 for i in 1:n]

        p_a    = count(recur_a)  / n
        p_px   = count(recur_px) / n
        p_both = count(i -> recur_a[i] && recur_px[i], 1:n) / n
        p_indep = p_a * p_px

        @printf("\n")
        @printf("  Co-localization test (recurring Δα vs recurring Δpx):\n")
        @printf("    Pr[Δα recurs]            = %.4f\n", p_a)
        @printf("    Pr[Δpx recurs]           = %.4f\n", p_px)
        @printf("    Pr[both recur]  observed = %.4f\n", p_both)
        @printf("    Pr[both recur]  indep.   = %.4f  (= Pr[Δα]×Pr[Δpx])\n", p_indep)
        if p_indep > 0
            lift = p_both / p_indep
            @printf("    Co-localization lift     = %.3fx\n", lift)
            if lift > 1.5
                @printf("    → Recurring Δα and recurring Δpx CO-LOCATE more than chance:\n")
                @printf("      closures cluster where the two concentrated sets overlap,\n")
                @printf("      consistent with GPT's hypothesis as stated (not just two\n")
                @printf("      independently concentrated marginals).\n")
            elseif lift < 0.67
                @printf("    → Recurring Δα and recurring Δpx are ANTI-correlated:\n")
                @printf("      whichever side is concentrated, it is not the same closures\n")
                @printf("      driving both — the two mechanisms look independent.\n")
            else
                @printf("    → No strong co-localization signal either way.\n")
            end
        end
    end

    # -----------------------------------------------------------------------
    #  Verdict — driven by the PRIMARY range test, not the collision stats
    #  above (which are mechanically uninformative at this n; see caveat).
    # -----------------------------------------------------------------------
    @printf("\n")
    @printf("  Verdict (from the range test, z = std-devs narrower than uniform predicts):\n")

    function _verdict_row(label::String, rt)
        rt === nothing && return
        if rt.z > 3
            @printf("    %-18s : CONCENTRATED  (z=%.2f, observed width = %.3e × ambient) —\n",
                    label, rt.z, rt.frac_of_ambient)
            @printf("    %-18s   support is significantly narrower than uniform predicts.\n", "")
        elseif rt.z < -3
            @printf("    %-18s : ANOMALY  (z=%.2f) — range WIDER than uniform predicts;\n",
                    label, rt.z)
            @printf("    %-18s   check units / mod-wraparound for this quantity.\n", "")
        else
            @printf("    %-18s : not distinguishable from uniform at n=%d  (z=%.2f).\n",
                    label, n, rt.z)
        end
    end

    _verdict_row("Δα  (combined_al)", rt_a)
    if beta_degenerate
        @printf("    %-18s : degenerate (single value) — likely β-tracking disabled; no verdict.\n",
                "Δβ  (combined_be)")
    else
        _verdict_row("Δβ  (combined_be)", rt_b)
    end
    _verdict_row("Δpx (FB anchor x)", rt_px)

    @printf("\n")
    @printf("    (Reference: observed α₂ ≈ 0.59–0.60 pinning. If a side is CONCENTRATED,\n")
    @printf("     its observed width/ambient ratio above is the relevant effective-support\n")
    @printf("     fraction for that side; compare it against 0.59–0.60 to judge whether it\n")
    @printf("     can explain the pinning alone or only partially. \"not distinguishable\n")
    @printf("     from uniform\" at this n does NOT rule out concentration — it means more\n")
    @printf("     closures are needed before the range test has power to detect it; rerun\n")
    @printf("     D35 once n has grown substantially before concluding this side is clean.)\n")

    @printf("\n")
    flush(stdout)
    return nothing
end
