# =============================================================================
#  lp1_conj_deep_diag_d35.jl
#
#  D35 — Closure difference-process concentration (Δα/Δβ vs ΔP proxy).
#
#  GPT's hypothesis, restated: a closure cancels the matching LP1-conj terms
#  and leaves
#       atom(fb[i0]) - atom(fb[prev_col])  =  Δα·G + Δβ·T
#  i.e. every closure is a coincidence between two *difference* processes —
#  RHS: Δα = combined_al, generated by sums of a finite increment table
#  (so may have high additive energy / small effective support even though
#  no single α ever repeats); LHS: P - P', generated by the FB-biased walk
#  (proxied here by Δpx, the x-coordinate difference of the two FB anchors,
#  consistent with every other px-based proxy elsewhere in this file).
#
#  The birthday null assumes Δα ~ Uniform(Z_ell) and (P-P') ~ Uniform(J).
#  D35 tests this directly: it computes the exact Rényi-2 effective support
#  S_eff = 1/Σp(x)² of the *closure-conditional* Δα and Δpx distributions
#  and compares each to its naive ambient size (ell, p respectively). It
#  also checks whether the two sides' concentrations co-localize (closures
#  cluster where both concentrated sets overlap) versus look concentrated
#  only individually/coincidentally.
#
#  Three independent verdicts fall out:
#    Δα side  concentrated  (S_eff_α << ell) → RHS culprit confirmed.
#    ΔP side  concentrated  (S_eff_P << p)   → LHS (FB geometry) contributes.
#    Neither concentrated                     → difference-process hypothesis
#                                                 itself falsified; α₂ pinning
#                                                 must come from elsewhere.
#
#  Included by lp1_conj_deep_diag.jl; do not include directly.
# =============================================================================

# ---------------------------------------------------------------------------
#  _renyi2_support — exact Rényi-2 effective support size from a value
#  vector: S_eff = 1 / Σ_x p(x)²  where p(x) = count(x)/n.
#  Returns (S_eff, counts_dict, sorted_desc_counts).
#  S_eff == 1.0 for a single repeated value, S_eff == n for n all-distinct
#  values (the "fully uniform, no collisions observed" case).
# ---------------------------------------------------------------------------
function _renyi2_support(vals::Vector{Int})
    n = length(vals)
    n == 0 && return (NaN, Dict{Int,Int}(), Int[])

    counts = Dict{Int,Int}()
    @inbounds for v in vals
        counts[v] = get(counts, v, 0) + 1
    end

    sum_p2 = 0.0
    nf = Float64(n)
    for (_, c) in counts
        p = c / nf
        sum_p2 += p * p
    end
    s_eff = sum_p2 > 0 ? 1.0 / sum_p2 : NaN

    sorted_desc = sort(collect(values(counts)), rev=true)
    return (s_eff, counts, sorted_desc)
end

# ---------------------------------------------------------------------------
#  _report_d35 — print the closure difference-process concentration report.
#
#  Arguments:
#    deep_stat — merged ConjDeepStat
#    p         — field characteristic (ambient size for the ΔP proxy side;
#                0 → skip ΔP analysis, Δα analysis still runs)
#    ell       — group order ℓ (ambient size for the Δα/Δβ side; 0 → skip)
# ---------------------------------------------------------------------------
function _report_d35(deep_stat::ConjDeepStat; p::Int = 0, ell::Int = 0)

    @printf("\n─── D35: closure difference-process concentration (Δα vs ΔP) ────────\n")

    n = length(deep_stat.d35_dalpha)
    @printf("  Closures recorded (capped at %d) : %d\n", D35_MAX_CLOSURES, n)
    @printf("  Closures seen (uncapped total)   : %d\n", deep_stat.d35_n_closures)

    if n < 4
        @printf("  (too few closures for D35 — skipping)\n\n")
        flush(stdout)
        return nothing
    end

    dalpha = deep_stat.d35_dalpha
    dbeta  = deep_stat.d35_dbeta

    # Δpx / Δpy computed here (not at record time) since p is only known
    # at report time. mod() handles negative raw differences correctly.
    have_p = p > 0
    dpx = have_p ? [mod(deep_stat.d35_px_close[i] - deep_stat.d35_px_store[i], p) for i in 1:n] : Int[]
    dpy = have_p ? [mod(deep_stat.d35_py_close[i] - deep_stat.d35_py_store[i], p) for i in 1:n] : Int[]

    # -----------------------------------------------------------------------
    #  Rényi-2 effective support: Δα, Δβ, Δpx
    # -----------------------------------------------------------------------
    s_eff_a,  counts_a,  sorted_a  = _renyi2_support(dalpha)
    s_eff_b,  counts_b,  sorted_b  = _renyi2_support(dbeta)
    s_eff_px, counts_px, sorted_px = have_p ? _renyi2_support(dpx) : (NaN, Dict{Int,Int}(), Int[])

    @printf("\n")
    @printf("  Rényi-2 effective support S_eff = 1/Σp(x)²  (n=%d closures):\n", n)
    @printf("  %-22s  %12s  %14s  %12s  %10s\n",
            "quantity", "S_eff", "ambient size", "S_eff/ambient", "vs n")
    @printf("  %s\n", "─"^78)

    function _row(label::String, s_eff::Float64, ambient::Int)
        if ambient > 0 && !isnan(s_eff)
            ratio = s_eff / ambient
            @printf("  %-22s  %12.2f  %14d  %12.3e  %10.3f\n",
                    label, s_eff, ambient, ratio, s_eff / n)
        elseif !isnan(s_eff)
            @printf("  %-22s  %12.2f  %14s  %12s  %10.3f\n",
                    label, s_eff, "n/a", "n/a", s_eff / n)
        else
            @printf("  %-22s  %12s\n", label, "n/a")
        end
    end

    _row("Δα  (combined_al)", s_eff_a, ell)
    _row("Δβ  (combined_be)", s_eff_b, ell)
    have_p && _row("Δpx (FB anchor x)", s_eff_px, p)

    # -----------------------------------------------------------------------
    #  Concentration shape: Gini / Hill exponent / top-share, reusing the
    #  same math helpers as D19/D33/D34 for a consistent vocabulary across
    #  the whole D-series.
    # -----------------------------------------------------------------------
    @printf("\n")
    @printf("  Concentration shape (0=uniform Gini, ∞=uniform Hill α, low top-5%%=uniform):\n")
    @printf("  %-22s  %10s  %12s  %12s\n", "quantity", "Gini", "Hill α(k=50)", "top-5% share")
    @printf("  %s\n", "─"^62)

    function _shape_row(label::String, sorted_desc::Vector{Int})
        isempty(sorted_desc) && return
        g  = _gini(sorted_desc)
        h  = _hill_exponent(sorted_desc; k=min(50, length(sorted_desc) - 1))
        ts = _top_share(sorted_desc, 0.05)
        @printf("  %-22s  %10.4f  %12.3f  %12.4f\n", label, g, h, ts)
    end

    _shape_row("Δα  (combined_al)", sorted_a)
    _shape_row("Δβ  (combined_be)", sorted_b)
    have_p && _shape_row("Δpx (FB anchor x)", sorted_px)

    # -----------------------------------------------------------------------
    #  Top-10 most frequent Δα / Δpx values, with share of closures.
    # -----------------------------------------------------------------------
    @printf("\n")
    @printf("  Top-10 most frequent Δα values:\n")
    @printf("  %-20s  %10s  %10s\n", "Δα value", "count", "share")
    @printf("  %s\n", "─"^44)
    top_a = sort(collect(counts_a), by = kv -> -kv[2])
    for (val, cnt) in top_a[1:min(10, length(top_a))]
        @printf("  %-20d  %10d  %10.4f\n", val, cnt, cnt / n)
    end

    if have_p
        @printf("\n")
        @printf("  Top-10 most frequent Δpx values:\n")
        @printf("  %-20s  %10s  %10s\n", "Δpx value", "count", "share")
        @printf("  %s\n", "─"^44)
        top_px = sort(collect(counts_px), by = kv -> -kv[2])
        for (val, cnt) in top_px[1:min(10, length(top_px))]
            @printf("  %-20d  %10d  %10.4f\n", val, cnt, cnt / n)
        end
    end

    # -----------------------------------------------------------------------
    #  Co-localization test: do recurring Δα and recurring Δpx happen at the
    #  SAME closures more than independence would predict? This is the
    #  direct test of "closures occur where the two concentrated sets
    #  overlap" rather than each side being concentrated for unrelated
    #  reasons. A "recurring" value is one whose count > 1 in the observed
    #  sample (i.e. this exact Δα — or Δpx — was hit by more than one
    #  closure).
    # -----------------------------------------------------------------------
    if have_p
        recur_a  = [counts_a[dalpha[i]]  > 1 for i in 1:n]
        recur_px = [counts_px[dpx[i]]    > 1 for i in 1:n]

        p_a    = count(recur_a)  / n
        p_px   = count(recur_px) / n
        p_both = count(i -> recur_a[i] && recur_px[i], 1:n) / n
        p_indep = p_a * p_px

        @printf("\n")
        @printf("  Co-localization test (recurring Δα vs recurring Δpx):\n")
        @printf("    Pr[Δα recurs]            = %.4f\n", p_a)
        @printf("    Pr[Δpx recurs]           = %.4f\n", p_px)
        @printf("    Pr[both recur]  observed = %.4f\n", p_both)
        @printf("    Pr[both recur]  indep.   = %.4f  (= Pr[Δα]×Pr[Δpx])\n", p_indep)
        if p_indep > 0
            lift = p_both / p_indep
            @printf("    Co-localization lift     = %.3fx\n", lift)
            if lift > 1.5
                @printf("    → Recurring Δα and recurring Δpx CO-LOCATE more than chance:\n")
                @printf("      closures cluster where the two concentrated sets overlap,\n")
                @printf("      consistent with GPT's hypothesis as stated (not just two\n")
                @printf("      independently concentrated marginals).\n")
            elseif lift < 0.67
                @printf("    → Recurring Δα and recurring Δpx are ANTI-correlated:\n")
                @printf("      whichever side is concentrated, it is not the same closures\n")
                @printf("      driving both — the two mechanisms look independent.\n")
            else
                @printf("    → No strong co-localization signal either way.\n")
            end
        end
    end

    # -----------------------------------------------------------------------
    #  Verdict
    # -----------------------------------------------------------------------
    @printf("\n")
    @printf("  Verdict:\n")
    if ell > 0 && !isnan(s_eff_a)
        ratio_a = s_eff_a / ell
        if ratio_a < 0.1
            @printf("    Δα  side : CONCENTRATED  (S_eff/ell = %.3e) — RHS culprit SUPPORTED.\n", ratio_a)
        else
            @printf("    Δα  side : not concentrated at this sample size (S_eff/ell = %.3e).\n", ratio_a)
        end
    end
    if have_p && !isnan(s_eff_px)
        ratio_px = s_eff_px / p
        if ratio_px < 0.1
            @printf("    ΔP  side : CONCENTRATED  (S_eff/p = %.3e) — FB-geometry amplifier SUPPORTED.\n", ratio_px)
        else
            @printf("    ΔP  side : not concentrated at this sample size (S_eff/p = %.3e).\n", ratio_px)
        end
    end
    @printf("    (Reference: observed α₂ ≈ 0.59–0.60 pinning. S_eff/ambient on the\n")
    @printf("     culprit side should sit in a comparable range if it fully explains\n")
    @printf("     the pinning on its own; well below that range implicates an even\n")
    @printf("     tighter bottleneck, well above it means this side alone is\n")
    @printf("     insufficient and the other side — or the overlap mechanism above —\n")
    @printf("     must be carrying the rest.)\n")

    @printf("\n")
    flush(stdout)
    return nothing
end
