#!/usr/bin/env julia
#
# Step 1: confirm cand1 is EXACTLY swap-symmetric (swap(cand1) == cand1
# as a polynomial identity, not just agreement on 5 sample points).
#
# Step 2: if confirmed, rewrite cand1 in symmetric variables s=t1+t2,
# q=t1*t2. A symmetric polynomial in 2 variables of total degree d has a
# unique expression in the elementary symmetric polynomials, computable
# via the standard elementary-symmetric-polynomial division algorithm
# (or just: cand1 as given already has degree <=5 in EACH of t1,t2
# individually per the printed monomials, e.g. t2^5*t1^4 -- so we can
# solve for the (s,q) rewrite by matching coefficients / polynomial
# division against s^i q^j).
#
# We do this with Oscar's built-in symmetric-function machinery, not by
# hand, so the reduction is verified by construction rather than by eye.

using Oscar

const p = 2371157
F = GF(p)

R, (w1, w2, t2, t1) = polynomial_ring(F, ["w1", "w2", "t2", "t1"])
swap_map = hom(R, R, [w2, w1, t1, t2])
swap(f) = swap_map(f)

curve1 = w1^2 - (t1^5 + t1 + 2)
curve2 = w2^2 - (t2^5 + t2 + 2)

D1 = t1^4 + 1869462*t1^3 + 1408746*t1^2 + 381595*t1 + 1827639
u1x0 = (76373*t1 + 1618225)*w1 + (463294*t1^4 + 1979687*t1^3 + 2039297*t1^2 + 1766020*t1 + 1466684)
u1x1 = (1178440*t1 + 76373)*w1 + (934731*t1^4 + 444430*t1^3 + 9875*t1^2 + 875375*t1 + 2041555)

Dv1 = t1^6 + 433036*t1^5 + 465199*t1^4 + 992136*t1^3 + 2332305*t1^2 + 554329*t1 + 1131637
v1x0 = (773065*t1^3 + 1247291*t1^2 + 2145997*t1 + 476917)*w1 +
       (1147392*t1^6 + 433228*t1^5 + 1812819*t1^4 + 2250585*t1^3 + 1416169*t1^2 + 624698*t1 + 2306090)
v1x1 = (519886*t1^3 + 504619*t1^2 + 758402*t1 + 13640)*w1 +
       (1781937*t1^6 + 304248*t1^5 + 1349490*t1^4 + 56951*t1^3 + 1916786*t1^2 + 208447*t1 + 176607)

D2 = t2^4 + 1773894*t2^3 + 1467*t2^2 + 2220726*t2 + 1449522
u2x0 = (76820*t2 + 1538127)*w2 + (1889274*t2^4 + 1720450*t2^3 + 1810757*t2^2 + 331956*t2 + 712643)
u2x1 = (1039068*t2 + 76820)*w2 + (886947*t2^4 + 442158*t2^3 + 801138*t2^2 + 1482032*t2 + 1152246)

Dv2 = t2^6 + 289684*t2^5 + 1450050*t2^4 + 1456351*t2^3 + 1812180*t2^2 + 2251389*t2 + 161448
v2x0 = (500276*t2^3 + 1901238*t2^2 + 644639*t2 + 1530220)*w2 +
       (2332747*t2^6 + 2126826*t2^5 + 1925741*t2^4 + 2296926*t2^3 + 1706749*t2^2 + 438582*t2 + 1647282)
v2x1 = (1488308*t2^3 + 280825*t2^2 + 143870*t2 + 535109)*w2 +
       (1851623*t2^6 + 904489*t2^5 + 1077359*t2^4 + 1072976*t2^3 + 2218875*t2^2 + 947498*t2 + 1259148)

function coeff_equal(num1, den1, num2, den2)
    return num1*den2 - num2*den1
end

Fu0 = coeff_equal(u1x0, D1, u2x0, D2)
Fu1 = coeff_equal(u1x1, D1, u2x1, D2)
Fv0 = coeff_equal(v1x0, Dv1, v2x0, Dv2)
Fv1 = coeff_equal(v1x1, Dv1, v2x1, Dv2)

Iuv = ideal(R, [Fu0, Fu1, Fv0, Fv1, curve1, curve2])

println("Eliminating w1, w2 ...")
It = eliminate(Iuv, [w1, w2])
gs = gens(It)
cand1 = gs[1]

println()
println("=== Step 1: exact symmetry check on cand1 ===")
diff = cand1 - swap(cand1)
println("cand1 - swap(cand1) == 0 ?  ", iszero(diff))
if !iszero(diff)
    println("NOT exactly symmetric. Nonzero difference has ", length(terms(diff)), " terms.")
    println("STOPPING -- do not trust an (s,q) rewrite if this fails.")
    exit(1)
end
println("Confirmed: cand1 is an EXACT polynomial identity under (t1,t2) swap.")
println()

################################################################################
# Step 2: rewrite cand1 in s = t1+t2, q = t1*t2.
#
# Method: build the target ring Rsq = F[s,q]. We know cand1 is symmetric
# of some bidegree (dt1_max, dt2_max) = (4,5) or (5,4) per the printed
# monomials (t2^5*t1^4 term visible), total degree 9. Any symmetric poly
# in F[t1,t2] of t1-degree,t2-degree <= n each lies in the subring
# generated by s,q and can be recovered by the standard algorithm:
# repeatedly subtract off the leading monomial's expression in s,q
# (via s^i q^j <-> elementary symmetric expansion) until nothing remains.
#
# Oscar doesn't have a one-line "rewrite symmetric poly in elementary
# symmetric variables" for a raw 2-var polynomial ring out of the box in
# all versions, so we do it constructively and CHECK by resubstitution,
# which is the trustworthy way to do this regardless.
################################################################################

Rst, (ss, qq) = polynomial_ring(F, ["s", "q"])

# t1, t2 are roots of X^2 - s*X + q = 0. We substitute t1 -> (generic) and
# reduce using t1+t2=s, t1*t2=q by expressing cand1 as a poly in t1 with
# coefficients that are symmetric functions of (t1,t2) built from s,q --
# constructive approach: use the "power sum / Newton's identity" ladder.
#
# Simpler and fully rigorous approach: substitute t2 = s - t1 into cand1,
# giving a polynomial in (t1, s). Since cand1 is symmetric in (t1,t2), the
# result, as a polynomial in t1 alone (with s as parameter), must be
# expressible using t1*(s-t1) = q, i.e. after substituting t2=s-t1, reduce
# modulo t1^2 - s*t1 + q repeatedly (using the relation t1^2 = s*t1 - q)
# until degree in t1 is <= 1. For a genuinely symmetric polynomial the
# remainder's t1-linear coefficient must vanish, leaving a pure (s,q)
# polynomial as the degree-0-in-t1 remainder. This is the standard
# elementary-symmetric reduction algorithm, done explicitly so we can
# assert the t1-linear part cancels (i.e. self-verifying).

# Work in F[t1, s] first (auxiliary ring), substitute t2 -> s - t1 into cand1.
Raux, (t1a, sa) = polynomial_ring(F, ["t1", "s"])

# Build a hom from R (4-var) restricted to the 2 vars appearing in cand1
# (t1,t2) into Raux, sending t1->t1a, t2-> sa - t1a. Since cand1 has no
# w1,w2 (elimination guarantees this), map those generators anywhere valid.
into_aux = hom(R, Raux, [zero(Raux), zero(Raux), sa - t1a, t1a])
cand1_aux = into_aux(cand1)

println("cand1 substituted with t2 = s - t1 has degree in t1: ",
        degree(cand1_aux, t1a))

# Reduce modulo t1^2 - s*t1 + q, i.e. replace t1^2 -> s*t1 - q repeatedly.
# We track the reduction as a polynomial in (t1, s, q) then confirm the
# t1-coefficient vanishes.
Raux2, (t1b, sb, qb) = polynomial_ring(F, ["t1", "s", "q"])
lift_hom = hom(Raux, Raux2, [t1b, sb])
poly = lift_hom(cand1_aux)

# Reduction loop: while degree in t1b >= 2, replace t1b^2 with sb*t1b - qb.
function reduce_deg2(poly, t1b, sb, qb)
    Rloc = parent(poly)
    while degree(poly, t1b) >= 2
        d = degree(poly, t1b)
        # extract leading coefficient (as poly in sb,qb) of t1b^d
        lc = coeff(poly, [t1b], [d])
        # t1b^d = t1b^(d-2) * t1b^2 -> t1b^(d-2)*(sb*t1b - qb)
        replacement = lc * gen(Rloc,1)^(d-2) * (sb*t1b - qb)
        poly = poly - lc*gen(Rloc,1)^d + replacement
    end
    return poly
end

reduced = reduce_deg2(poly, t1b, sb, qb)
println("After reduction mod (t1^2 - s*t1 + q), degree in t1: ", degree(reduced, t1b))

# The t1-linear coefficient must be zero for cand1 to be a genuine (s,q)
# polynomial (this is the self-check).
lin_coeff = coeff(reduced, [t1b], [1])
const_part = coeff(reduced, [t1b], [0])

println("t1-linear coefficient after reduction (should be 0): ", iszero(lin_coeff) ? "0  [OK]" : lin_coeff)

if !iszero(lin_coeff)
    println("FAILED: cand1 does not reduce cleanly to a pure (s,q) polynomial.")
    println("Linear-in-t1 remainder has ", length(terms(lin_coeff)), " terms -- inspect before trusting anything downstream.")
    exit(1)
end

println()
println("=== cand1 rewritten in symmetric variables s=t1+t2, q=t1*t2 ===")
println("degree in s: ", degree(const_part, sb))
println("degree in q: ", degree(const_part, qb))
println("terms: ", length(terms(const_part)))
println()
println(const_part)
println()

# Final correctness check: re-substitute s=t1+t2, q=t1*t2 back into the
# (s,q) polynomial using the ORIGINAL 4-variable ring and confirm it
# matches cand1 exactly, on the nose, as polynomials (not just at sample
# points).
back_hom = hom(Raux2, R, [zero(R), t1+t2, t1*t2])  # t1b unused after reduction succeeded, but hom needs full domain
# Since const_part has no t1b, this is safe regardless of the first slot.
recon = back_hom(const_part)

println("=== Final verification: resubstitute and compare to original cand1 ===")
println("recon - cand1 == 0 ?  ", iszero(recon - cand1))
