# =============================================================================
#  trial3_amortized.jl  —  Amortized DLP infrastructure
#
#  Two independent but complementary ideas:
#
#  1. ALPHA-ONLY PRECOMPUTATION  (amortize_alpha_phase)
#     ─────────────────────────────────────────────────
#     The insight: if we suppress β (set β=0 in every walk step during
#     precomputation), every relation has the form
#
#         FB-atoms  =  α·G                 (β-free)
#
#     Gaussian elim on this over-determined system gives us a dictionary
#
#         atom_log[pt]  =  log_G(pt)  ∈ Z/ell
#
#     for every factor-base atom.  This is the *precomputation* phase and
#     only needs to be done once for the group.
#
#     Then for a new target T, we collect a *single* β≠0 relation:
#
#         c₁·pt₁ + c₂·pt₂ + c₃·pt₃  =  α·G + β·T      (β≠0)
#
#     Substituting the known atom logs:
#
#         α + β·k  ≡  c₁·log[pt₁] + c₂·log[pt₂] + c₃·log[pt₃]  (mod ell)
#         k  =  (RHS − α) · β⁻¹  mod ell
#
#     This makes all subsequent DLPs O(polylog p) after the precomputation.
#
#     Why Lp3-suppression enables this:
#     With only Lp1 (and Lp2 spanning-tree) relations, every relation
#     involves at most 2 non-FB atoms, which close under the spanning tree.
#     The resulting matrix has H₂ = 0 (no independent 2-cycles in the
#     chain complex), so the atom-log map extends uniquely from the spanning
#     tree.  This is the algebraic reason β-free relations suffice to fix
#     all atom logs.
#
#  2. O(n) CYCLE-UNION LA SOLVER  (cycle_union_solve)
#     ─────────────────────────────────────────────────
#     Classical observation: if H₂ = 0, the relation matrix (over Z/ell)
#     viewed as the boundary map ∂₁ of a 1-complex has trivial second
#     homology.  The kernel of ∂₁ is generated by the *cycles* of the
#     factor-base graph.  Finding a kernel vector = finding a cycle.
#
#     Algorithm (union-find, O(n α(n))):
#       - Build a graph G on factor-base vertices.
#       - Each relation row is an (hyper)edge on its support.
#       - Process rows with a DSU.  When inserting a row creates a cycle,
#         that cycle is a kernel vector — read it off from the DSU path.
#       - Under H₂=0 every kernel vector arises this way.
#
#     The recovered kernel vectors satisfy:
#       γᵢ · rel_matrix = 0  over GF(ell)
#     and we solve  k = −(γ·α)(γ·β)⁻¹  as usual.
#
#     Complexity: O(n · α(n))  where n = |relations|,
#     vs O(n · m · min(n,m)) for dense Gaussian elimination.
#
#     NOTE: the H₂=0 hypothesis is *conjectural* for this walk.  The solver
#     falls back to left_kernel_all() if cycle extraction fails to produce a
#     valid k.  The flag `cycle_solver_succeeded` in the return value tells
#     you which path was taken.
#
# =============================================================================

# ---------------------------------------------------------------------------
#  DSU (Disjoint Set Union) with path compression and union-by-rank,
#  augmented to track the *path label* (sum of edge weights mod ell) needed
#  to reconstruct the cycle vector.
#
#  Label convention: label[v] is the value L such that
#      atom_log[v]  ≡  atom_log[root(v)] + L   (mod ell)
#  along the DSU tree path.  When two components are merged by edge (u,v,w):
#      atom_log[u]  +  w  ≡  atom_log[v]        (the relation says so)
#  so label[u] is set appropriately during union.
# ---------------------------------------------------------------------------
mutable struct LabelledDSU
    parent ::Vector{Int}
    rank   ::Vector{Int}
    label  ::Vector{Int}   # label[v] = offset from root, mod ell
    ell    ::Int
end

function LabelledDSU(n::Int, ell::Int)
    LabelledDSU(collect(1:n), zeros(Int, n), zeros(Int, n), ell)
end

# Find root of v; path-compress and accumulate label offset.
# Returns (root, label_v_to_root) where label_v_to_root satisfies
#     atom_log[v] ≡ atom_log[root] + label_v_to_root  (mod ell)
function dsu_find(d::LabelledDSU, v::Int)
    if d.parent[v] == v
        return v, 0
    end
    root, plabel = dsu_find(d, d.parent[v])
    # Path compress
    d.label[v]  = mod(d.label[v] + plabel, d.ell)
    d.parent[v] = root
    return root, d.label[v]
end

# Try to union components of u and v given the constraint:
#   coeff_u · atom_log[u]  +  coeff_v · atom_log[v]  ≡  rhs  (mod ell)
# Simplified to weight w: atom_log[u] - atom_log[v] ≡ w  (when coeff_u=1, coeff_v=-1).
#
# More generally we handle the binary case: the caller pre-computes w for us.
#
# Returns:
#   :merged   — components were distinct; merged successfully.
#   :cycle    — components were the same; cycle detected.  The cycle-weight
#               (= the residual mod ell that should be zero if the relation
#               is consistent) is returned as cycle_weight.
function dsu_union!(d::LabelledDSU, u::Int, v::Int, w::Int)
    ru, lu = dsu_find(d, u)
    rv, lv = dsu_find(d, v)

    if ru == rv
        # Cycle: the residual is  lu - lv - w  mod ell.
        cycle_weight = mod(lu - lv - w, d.ell)
        return :cycle, cycle_weight
    end

    # Merge smaller rank into larger.
    if d.rank[ru] < d.rank[rv]
        ru, rv = rv, ru
        lu, lv = lv, lu
        w = mod(-w, d.ell)
    end
    # Now ru is the new root.
    # We need label[rv] such that atom_log[rv] ≡ atom_log[ru] + label[rv].
    # From atom_log[u] - atom_log[v] ≡ w and lu,lv:
    #   atom_log[u] = atom_log[ru] + lu
    #   atom_log[v] = atom_log[rv_new_root=ru] + label[rv]
    #   (atom_log[ru] + lu) - (atom_log[ru] + label[rv]) ≡ w
    #   label[rv] ≡ lu - w  (mod ell)  ... but rv's root was rv, so adjust for lv:
    #   atom_log[rv_old] ≡ atom_log[ru] + label[rv_old]
    #   atom_log[v]      = atom_log[rv_old] + lv  ≡  atom_log[ru] + label[rv_old] + lv
    #   atom_log[u]      = atom_log[ru] + lu
    #   lu - (label[rv_old] + lv) ≡ w  →  label[rv_old] = lu - lv - w
    d.label[rv]  = mod(lu - lv - w, d.ell)
    d.parent[rv] = ru
    d.rank[ru] == d.rank[rv] && (d.rank[ru] += 1)
    return :merged, 0
end

# ---------------------------------------------------------------------------
#  cycle_union_solve
#
#  O(n · α(n)) kernel / atom-log solver under the H₂=0 hypothesis.
#
#  The key insight: every phi-walk relation has exactly weight 3 (atoms P0, R, S).
#  The relation is:
#
#       log[P0] + log[R] + log[S]  ≡  α + β·k   (mod ell)
#
#  This is a *ternary* hyperedge on the factor-base graph.  We handle it by
#  building a spanning tree of the factor-base graph via iterative reduction:
#
#    - Maintain a DSU with labels: label[v] = log[v] - log[root(v)]  (mod ell).
#    - Each ternary row (u, v, w) has rhs = α_i + β_i·k (unknown k).
#      We track it as:  log[u] + log[v] + log[w] = rhs_i  (with rhs_i partially
#      unknown due to k, but we treat rhs_i as a symbolic affine function of k).
#    - Instead of carrying k symbolically, we use the following trick:
#
#      Once the DSU has placed two of the three atoms in the same component
#      (their logs are known relative to the root), the third atom's log is
#      determined up to the root's unknown.  When a relation closes a cycle
#      (all three atoms already in the same component), we get a constraint
#      on α + β·k and can solve for k.
#
#  Concretely:
#    log[u] = label[u] + log[root_u]     (from DSU)
#    log[v] = label[v] + log[root_v]
#    log[w] = label[w] + log[root_w]
#
#  Case A: root_u = root_v = root_w  (full cycle)
#    label[u] + label[v] + label[w] + log[root] · (coeff_u + coeff_v + coeff_w)
#        ≡ α_i + β_i·k
#    With unit coefficients (all +1):
#    (label[u] + label[v] + label[w]) + 3·log[root] ≡ α_i + β_i·k
#    But log[root] is unknown unless pinned.  So we maintain per-component a
#    symbolic "root log" variable R_c ∈ Z/ell, and when two components merge
#    we eliminate one variable.
#
#  This becomes exactly sparse Gaussian elimination, just structured so that
#  under H₂=0 the component-graph is a forest and we process it in O(n).
#
#  Implementation: we use a two-level approach:
#    Level 1 – DSU on factor-base atoms (nF vertices), labelled with
#              log[v] - log[root(v)].
#    Level 2 – "component log" system: one unknown per DSU component.
#              Each relation, once reduced to component-log variables, gives
#              one linear equation.  Under H₂=0 and unit coefficients this
#              system is sparse (weight ≤ 3) and acyclic (tree), so it
#              resolves greedily in O(n).
#
#  In the weight-3 / all-coefficients-+1 case (which is what the phi walk
#  produces), the component-log system is itself a 3-uniform hypergraph, and
#  we apply the same iterative reduction to it.
#
#  Returns NamedTuple:
#    k                      — Int or nothing
#    atom_logs              — Vector{Int} or nothing
#    cycle_solver_succeeded — Bool
#    n_cycles_found         — Int
#    n_deferred_resolved    — Int
# ---------------------------------------------------------------------------
function cycle_union_solve(rel_rows   ::Vector{Dict{Int,Int}},
                           alpha_vec  ::Vector{BigInt},
                           beta_vec   ::Vector{BigInt},
                           nF         ::Int,
                           ell        ::Int;
                           G          ::Union{Nothing,Div2} = nothing,
                           T          ::Union{Nothing,Div2} = nothing,
                           verbose    ::Bool = true)

    m = length(rel_rows)
    m == 0 && return (k=nothing, atom_logs=nothing,
                      cycle_solver_succeeded=false, n_cycles_found=0,
                      n_deferred_resolved=0)

    # ------------------------------------------------------------------
    #  Level-1 DSU: track atom-log offsets from component roots.
    #  label[v]  =  log[v] - log[root(v)]   mod ell
    #  When log[root(v)] is known (pinned), log[v] = label[v] + log[root].
    # ------------------------------------------------------------------
    dsu        = LabelledDSU(nF, ell)
    root_log   = fill(-1, nF)   # root_log[r] = known log of root r; -1 = unknown
    # atom_log[v] = known absolute log of v; -1 = unknown
    atom_log   = fill(-1, nF)

    # Pin root r's log to val, propagate to all atoms in its component.
    function pin_root!(r::Int, val::Int)
        root_log[r] = mod(val, ell)
        # Propagate to all atoms whose find() == r.
        # (Lazy: we'll recompute atom_log on demand via dsu_find.)
    end

    # Get atom log if known, else -1.
    function get_atom_log(v::Int)::Int
        r, lv = dsu_find(dsu, v)
        rl = root_log[r]
        rl == -1 && return -1
        return mod(lv + rl, ell)
    end

    # Merge components of u and v with edge constraint:
    #   coeff_u · log[u] + coeff_v · log[v] ≡ rhs_known  (mod ell)
    # where rhs_known is the part of the relation rhs after subtracting
    # contributions of already-resolved atoms.
    # Returns :cycle if both were already in the same component.
    function merge_binary!(u::Int, cu::Int, v::Int, cv::Int, rhs::Int)
        ru, lu = dsu_find(dsu, u)
        rv, lv = dsu_find(dsu, v)

        if ru == rv
            return :cycle
        end

        # We need: cu*(lu + R_ru) + cv*(lv + R_rv) ≡ rhs
        # After merge, one root disappears.  If R_ru is known:
        #   cv*(lv + R_rv) ≡ rhs - cu*(lu + R_ru)
        #   R_rv ≡ (rhs - cu*(lu + R_ru) - cv*lv) / cv
        if root_log[ru] != -1
            known_part = mod(rhs - cu * (lu + root_log[ru]), ell)
            cv_inv     = powermod(mod(cv, ell), ell - 2, ell)
            R_rv_val   = mod((known_part - cv * lv) * cv_inv, ell)
            # Perform the DSU merge: ru absorbs rv (or vice versa, doesn't matter
            # for correctness since we track root_log separately).
            dsu_union!(dsu, u, v, 0)   # structural merge; labels get recomputed
            new_r, _ = dsu_find(dsu, u)
            root_log[new_r] = (new_r == ru) ? root_log[ru] :
                               mod(root_log[ru] - lu, ell)   # adjust for new root
            # Pin the now-merged component with R_rv info baked in.
            pin_root!(new_r, (new_r == ru) ? root_log[ru] : R_rv_val)
        elseif root_log[rv] != -1
            known_part = mod(rhs - cv * (lv + root_log[rv]), ell)
            cu_inv     = powermod(mod(cu, ell), ell - 2, ell)
            R_ru_val   = mod((known_part - cu * lu) * cu_inv, ell)
            dsu_union!(dsu, u, v, 0)
            new_r, _ = dsu_find(dsu, u)
            pin_root!(new_r, (new_r == rv) ? root_log[rv] : R_ru_val)
        else
            # Neither root is pinned; just merge structurally.
            # Record the constraint for later resolution.
            dsu_union!(dsu, u, v, 0)
        end
        return :merged
    end

    # ------------------------------------------------------------------
    #  Process all relations in a work-queue loop.
    #  Each relation is processed when enough of its atoms are resolved
    #  to determine at least one new atom or detect a cycle (→ solve k).
    # ------------------------------------------------------------------
    n_cycles           = 0
    n_deferred_resolved = 0
    k_candidate        = nothing

    function try_recover_k(ri::Int)
        Sa = mod(alpha_vec[ri], ell)
        Sb = mod(beta_vec[ri],  ell)
        Sb == 0 && return nothing
        k = mod(-Int(Sa) * powermod(Int(Sb), ell - 2, ell), ell)
        if G !== nothing && T !== nothing
            jac_mul(G, k, ell) == T || return nothing
        end
        return k
    end

    # Work queue: indices of unresolved relations.
    pending   = collect(1:m)
    n_passes  = 0
    max_passes = m + 2   # safety cap; under H₂=0 should terminate in ≤ n passes

    while !isempty(pending) && n_passes < max_passes
        n_passes += 1
        next_pending = Int[]
        made_progress = false

        for ri in pending
            row     = rel_rows[ri]
            support = [(j, mod(v, ell)) for (j, v) in row if mod(v, ell) != 0 && 1 <= j <= nF]
            isempty(support) && continue

            # Compute known-log contribution and collect unknown atoms.
            rhs_known    = mod(Int(alpha_vec[ri]) + Int(beta_vec[ri]), ell)
            # (α + β absorbed into rhs; k is implicitly 0 for tree-building,
            #  and we solve for k when a cycle closes.)
            # Actually: rhs = α_i (pretend k=1 for tree; correct at cycle close).
            # We track everything symbolically as:
            #   sum_j  coeff_j * log[j]  ≡  alpha_i + beta_i * k
            # and at cycle-close we have all logs known → solve for k.

            known_sum  = 0
            unknown    = Tuple{Int,Int}[]   # (atom_idx, coeff)
            for (j, cj) in support
                lj = get_atom_log(j)
                if lj != -1
                    known_sum = mod(known_sum + cj * lj, ell)
                else
                    push!(unknown, (j, cj))
                end
            end

            n_unk = length(unknown)

            if n_unk == 0
                # Cycle: all atoms known.  Check consistency → solve for k.
                n_cycles += 1
                # known_sum ≡ alpha_i + beta_i * k
                # k = (known_sum - alpha_i) * beta_i^{-1}
                ai = mod(Int(alpha_vec[ri]), ell)
                bi = mod(Int(beta_vec[ri]),  ell)
                if bi != 0
                    k_try = mod((known_sum - ai) * powermod(bi, ell - 2, ell), ell)
                    if G !== nothing && T !== nothing
                        if jac_mul(G, k_try, ell) == T
                            k_candidate = k_try
                            verbose && @printf("[cycle_union] Cycle at row %d → k=%d ✓\n", ri, k_candidate)
                        end
                    else
                        k_candidate === nothing && (k_candidate = k_try)
                    end
                end
                made_progress = true

            elseif n_unk == 1
                # One unknown: pin it.
                j_unk, cj = unknown[1]
                ai  = mod(Int(alpha_vec[ri]), ell)
                bi  = mod(Int(beta_vec[ri]),  ell)
                # known_sum + cj*log[j_unk] ≡ ai + bi*k
                # We don't know k, so we can only pin if bi==0 (α-only relation).
                # If bi != 0, defer until k is known.
                if bi == 0
                    cj_inv   = powermod(cj, ell - 2, ell)
                    log_j    = mod((ai - known_sum) * cj_inv, ell)
                    r_j, lj  = dsu_find(dsu, j_unk)
                    pin_root!(r_j, mod(log_j - lj, ell))
                    made_progress = true
                    n_deferred_resolved += 1
                elseif k_candidate !== nothing
                    # k is now known; resolve immediately.
                    rhs_full = mod(ai + bi * k_candidate, ell)
                    cj_inv   = powermod(cj, ell - 2, ell)
                    log_j    = mod((rhs_full - known_sum) * cj_inv, ell)
                    r_j, lj  = dsu_find(dsu, j_unk)
                    pin_root!(r_j, mod(log_j - lj, ell))
                    made_progress = true
                    n_deferred_resolved += 1
                else
                    push!(next_pending, ri)
                end

            elseif n_unk == 2
                # Two unknowns: gives a binary DSU edge (modulo k being unknown).
                # We can at least merge the two components structurally.
                # If one component root is pinned and k is known (or bi==0), we
                # can also pin the other.
                (j1, c1), (j2, c2) = unknown[1], unknown[2]
                ai = mod(Int(alpha_vec[ri]), ell)
                bi = mod(Int(beta_vec[ri]),  ell)
                rhs_effective = bi == 0 ? mod(ai - known_sum, ell) :
                                k_candidate !== nothing ?
                                    mod(ai + bi * k_candidate - known_sum, ell) : -1

                if rhs_effective != -1
                    status = merge_binary!(j1, c1, j2, c2, rhs_effective)
                    status == :cycle && (n_cycles += 1)
                    made_progress = true
                else
                    # Structural-only merge (no rhs known yet).
                    dsu_union!(dsu, j1, j2, 0)
                    push!(next_pending, ri)
                end

            else
                # Three or more unknowns: defer.
                push!(next_pending, ri)
            end
        end

        pending = next_pending
        !made_progress && break
    end

    # Build atom_logs from DSU + root_log.
    atom_logs = nothing
    try
        logs = Vector{Int}(undef, nF)
        for v in 1:nF
            logs[v] = get_atom_log(v)
        end
        atom_logs = logs
    catch
    end

    if verbose
        n_pinned = count(v -> get_atom_log(v) != -1, 1:nF)
        @printf("[cycle_union] %d cycles found, %d deferred resolved, %d/%d atoms pinned, k=%s\n",
                n_cycles, n_deferred_resolved, n_pinned, nF,
                k_candidate === nothing ? "nothing" : string(k_candidate))
    end

    return (k                      = k_candidate,
            atom_logs              = atom_logs,
            cycle_solver_succeeded = k_candidate !== nothing,
            n_cycles_found         = n_cycles,
            n_deferred_resolved    = n_deferred_resolved)
end

# ---------------------------------------------------------------------------
#  amortize_alpha_phase
#
#  Run the walk collecting ONLY β=0 relations.  This fills a factor-base
#  dictionary  atom_log[pt] = log_G(pt)  for all pts in the FB.
#
#  Concretely: in phase1_walk and the phase2_worker, we hard-set β=0 before
#  building D = α·G (so T is never mixed in).  Every relation then has the form
#
#       sum_i c_i · [pt_i]  =  α · G + 0 · T
#
#  and left_kernel_all (or cycle_union_solve) on the resulting matrix gives us
#  the left null space.  But what we actually want is the *particular solution*
#  to the overdetermined system.  We use a single pinning row:
#
#       pin relation: G is in FB at index 0 (virtual), with log = 1.
#
#  Then RREF gives atom_log[v] = rhs for each variable column.
#
#  Returns:
#    atom_log_dict :: Dict{NTuple{2,Int}, Int}  — pt → log_G(pt) mod ell
#    fb            :: Vector{NTuple{2,Int}}
#    ell           :: Int
# ---------------------------------------------------------------------------
function amortize_alpha_phase(G::Div2, ell::Int;
                               fb_size   ::Int  = 500,
                               verbose   ::Bool = true)
    verbose && println("\n── Amortised precomputation: α-only walk ───────────────────────────")
    verbose && @printf("  FB target: %d atoms,  β forced to 0\n", fb_size)

    seed_pts = curve_points()
    isempty(seed_pts) && error("No rational curve points")

    fb      = sizehint!(NTuple{2,Int}[], fb_size)
    pt2idx  = sizehint!(Dict{NTuple{2,Int},Int}(), fb_size)
    alpha_vec = BigInt[]
    rel_rows  = Vector{Dict{Int,Int}}()

    function maybe_add!(pt)
        haskey(pt2idx, pt) && return
        length(fb) >= fb_size && return
        push!(fb, pt); pt2idx[pt] = length(fb)
    end

    cur_pt = seed_pts[rand(1:length(seed_pts))]
    maybe_add!(cur_pt)

    raw_steps = 0
    t0        = time()

    while length(fb) < fb_size || length(rel_rows) < length(fb) + 2
        raw_steps += 1
        α = rand(1:ell-1)
        # β = 0  — α-only walk
        D = jac_mul(G, α, ell)

        fp3_deg(D.u) != 2 && continue

        u0 = D.u[1]; u1 = D.u[2]; v0 = D.v[1]; v1 = D.v[2]
        px, py = cur_pt
        upx = fp(fp(px*px) + fp(u1*px) + u0)
        upx == 0 && continue

        phi_c = build_phi_mumford(px, py, u0, u1, v0, v1)
        phi_c === nothing && continue
        a, b, c, _ = phi_c

        R, S, rs_mumford = phi_residual_mumford(a, b, c, px, u0, u1)
        rs_mumford === SENTINEL_MUMFORD && continue
        R === SENTINEL_PT && continue

        r_new = !haskey(pt2idx, R)
        s_new = !haskey(pt2idx, S)
        slots_free = fb_size - length(fb)
        (r_new ? 1 : 0) + (s_new ? 1 : 0) > slots_free && continue

        maybe_add!(R); maybe_add!(S)

        i0 = pt2idx[cur_pt]; iR = pt2idx[R]; iS = pt2idx[S]
        row = Dict{Int,Int}()
        for idx in (i0, iR, iS)
            row[idx] = get(row, idx, 0) + 1
        end
        neg_al = mod(ell - α, ell)
        push!(alpha_vec, BigInt(neg_al))
        push!(rel_rows, row)

        cur_pt = R
    end

    nF = length(fb)

    if verbose
        @printf("  α-walk done: %d steps, %d FB atoms, %d relations (%.2fs)\n",
                raw_steps, nF, length(rel_rows), time() - t0)
    end

    # Solve: find atom_logs via RREF of the (m × nF) relation matrix over GF(ell).
    # We want the *particular solution* (not the kernel), so we augment with
    # a pinning row: [fb_atom_0_col = 1, rhs_col = 1]  (the first atom has log = 1
    # as a convention, or we use a known generator if we find G in the FB).
    #
    # For simplicity, use Nemo RREF to get the row-reduced form and read off
    # the unique solution (if the system is consistent and full-rank).
    atom_log_dict = Dict{NTuple{2,Int}, Int}()

    try
        F       = Nemo.GF(ell)
        m       = length(rel_rows)
        # Build augmented [A | b] where b[i] = alpha_vec[i] (RHS of atom_log system)
        # System: A · x ≡ alpha_vec  (mod ell),  x = atom_logs
        aug = zero_matrix(F, m, nF + 1)
        for i in 1:m
            for (j, v) in rel_rows[i]
                1 <= j <= nF || continue
                aug[i, j] = mod(v, ell)
            end
            aug[i, nF + 1] = mod(alpha_vec[i], ell)
        end
        _, R_mat = rref(aug)   # Nemo rref returns (rank, rref_matrix)

        # Read off the solution: for each pivot row, x[pivot_col] = rhs / pivot_val.
        logs = zeros(Int, nF)
        for r in 1:nrow(R_mat)
            # Find pivot column.
            pc = 0
            for c in 1:nF
                R_mat[r, c] != 0 && (pc = c; break)
            end
            pc == 0 && continue
            logs[pc] = Int(lift(ZZ, R_mat[r, nF + 1]))
        end

        for (pt, idx) in pt2idx
            atom_log_dict[pt] = logs[idx]
        end

        if verbose
            n_nonzero = count(!=(0), logs)
            @printf("  atom_log dictionary: %d / %d atoms with non-zero log\n",
                    n_nonzero, nF)
        end
    catch e
        @warn "amortize_alpha_phase: RREF solve failed ($e). Returning empty dict."
    end

    return (atom_log_dict = atom_log_dict, fb = fb, ell = ell)
end

# ---------------------------------------------------------------------------
#  amortized_dlp
#
#  Given a precomputed atom_log_dict from amortize_alpha_phase, recover the
#  discrete log of an arbitrary target T with a *single* β≠0 relation.
#
#  We walk until we find one step where:
#    - P0, R, S are all in the factor base (0-LP), AND
#    - β ≠ 0 (so T is present in the relation)
#
#  Then k = (c₀·log[P0] + cR·log[R] + cS·log[S] − α) · β⁻¹  mod ell.
#
#  In the LP1-suppressed regime (Lp3=0) a single β≠0 step always exists
#  because the FB covers Θ(√p) of the p points, so the 0-LP probability
#  is (FB/p)² ~ 1/p, and we expect O(p) steps — still O(polylog p) total
#  if the FB was built once.  Actually for √p FB and p-curve this is
#  p/(√p)² = 1 step per O(1) walk steps in expectation.  Very fast.
#
#  Returns k::Int or nothing on failure.
# ---------------------------------------------------------------------------
function amortized_dlp(G          ::Div2,
                       T          ::Div2,
                       atom_log_dict::Dict{NTuple{2,Int}, Int},
                       fb         ::Vector{NTuple{2,Int}},
                       ell        ::Int;
                       max_steps  ::Int  = 10_000_000,
                       verbose    ::Bool = true)

    pt2idx = Dict(pt => i for (i, pt) in enumerate(fb))
    nF     = length(fb)
    nF == 0 && error("empty factor base")

    verbose && @printf("\n── Amortised DLP solve: single β≠0 step ───────────────────────────\n")

    t0 = time()
    for step in 1:max_steps
        α = BigInt(rand(1:ell-1))
        β = BigInt(rand(1:ell-1))   # β ≠ 0 by construction
        D = jac_add(jac_mul(G, Int(α % ell), ell),
                    jac_mul(T, Int(β % ell), ell))
        fp3_deg(D.u) != 2 && continue

        u0 = D.u[1]; u1 = D.u[2]; v0 = D.v[1]; v1 = D.v[2]

        # Pick a random FB point as anchor.
        cur_pt = fb[rand(1:nF)]
        px, py = cur_pt
        upx = fp(fp(px*px) + fp(u1*px) + u0)
        upx == 0 && continue

        phi_c = build_phi_mumford(px, py, u0, u1, v0, v1)
        phi_c === nothing && continue
        a, b, c, _ = phi_c

        R, S, rs_mumford = phi_residual_mumford(a, b, c, px, u0, u1)
        rs_mumford === SENTINEL_MUMFORD && continue
        R === SENTINEL_PT && continue

        # 0-LP check: all three in FB.
        haskey(pt2idx, cur_pt) && haskey(pt2idx, R) && haskey(pt2idx, S) || continue

        i0 = pt2idx[cur_pt]
        iR = pt2idx[R]
        iS = pt2idx[S]

        row = Dict{Int,Int}()
        for idx in (i0, iR, iS)
            row[idx] = get(row, idx, 0) + 1
        end

        # Compute RHS from atom_log_dict.
        rhs = 0
        ok  = true
        for (j, c_j) in row
            pt_j = fb[j]
            haskey(atom_log_dict, pt_j) || (ok = false; break)
            rhs = mod(rhs + c_j * atom_log_dict[pt_j], ell)
        end
        ok || continue

        neg_α = mod(ell - Int(α % ell), ell)
        neg_β = mod(ell - Int(β % ell), ell)

        # Relation: rhs ≡ neg_α + neg_β · k   ←  wait, sign convention:
        # Our walk convention: [P0] + [R] + [S] + neg_α·G + neg_β·T = 0
        # ⇒ log[P0] + log[R] + log[S] ≡ α + β·k  (mod ell)
        # ⇒ k = (rhs − α) · β⁻¹  mod ell
        k_cand = mod((rhs - Int(α % ell)) * powermod(Int(β % ell), ell - 2, ell), ell)
        k_cand = mod(k_cand, ell)

        if jac_mul(G, k_cand, ell) == T
            verbose && @printf("  ✓ k = %d  found after %d steps (%.3fs)\n",
                               k_cand, step, time() - t0)
            return k_cand
        end
    end

    verbose && @printf("  amortized_dlp: no valid step found in %d attempts\n", max_steps)
    return nothing
end

# ---------------------------------------------------------------------------
#  Wrappers: drop-in replacements for the main2() flow
# ---------------------------------------------------------------------------

"""
    run_amortized(; fb_size, verbose)

Full amortised pipeline:
  1. Bootstrap G, ell via frobenius_find_ell_generator.
  2. Build atom_log_dict via amortize_alpha_phase (β=0 walk).
  3. For a given T, call amortized_dlp (single β≠0 relation).

This replaces the combined walk+kernel-solve with:
  precompute:  O(p · polylog p)   [once per (curve, p)]
  per-DLP:     O(polylog p)       [each new T]
"""
function run_amortized(; fb_size  ::Int  = 500,
                         verbose  ::Bool = true,
                         n_targets::Int  = 3)

    t0   = time()
    pts  = curve_points()
    G, ell_found = frobenius_find_ell_generator(pts)
    global ell = ell_found

    @printf("ell = %d  (%.1f bits)\n", ell, log2(ell))

    # Precomputation: β=0 walk.
    pre = amortize_alpha_phase(G, ell; fb_size=fb_size, verbose=verbose)
    @printf("Precomputation done in %.3fs.  Dict size: %d atoms.\n",
            time() - t0, length(pre.atom_log_dict))

    # Solve multiple independent DLPs to demonstrate amortisation.
    for trial in 1:n_targets
        k_true = rand(2:ell-1)
        T      = jac_mul(G, k_true, ell)
        @printf("\n[Trial %d] k_true = %d\n", trial, k_true)
        k_rec  = amortized_dlp(G, T, pre.atom_log_dict, pre.fb, ell;
                                verbose=verbose)
        if k_rec !== nothing
            @printf("  match = %s\n", k_rec == k_true)
        else
            @printf("  FAILED\n")
        end
    end
end

"""
    run_cycle_union_solve(G, T; fb_size, verbose)

Drop-in alternative to the left_kernel_all path in index_calculus_walk.
Collects relations normally (with β≠0), then solves via cycle_union_solve
(O(n) under H₂=0) before falling back to left_kernel_all.
"""
function run_cycle_union_solve(G::Div2, T::Div2;
                                fb_size ::Int  = 500,
                                verbose ::Bool = true)

    pts  = curve_points()
    nall = length(pts)

    # Phase 1 as usual.
    fb, pt2idx, p1_alpha, p1_beta, p1_rows =
        phase1_walk(G, T, fb_size; verbose=verbose)
    nF = length(fb)

    # Collect a minimal set of phase-2 relations.
    rel_target   = nF + 20
    rel_counter  = Threads.Atomic{Int}(0)
    step_D, step_a, step_b = begin
        N = 256; sD = Vector{Div2}(undef, N)
        sa = Vector{BigInt}(undef, N); sb = Vector{BigInt}(undef, N)
        for i in 1:N
            a = BigInt(rand(1:ell-1)); b = BigInt(rand(1:ell-1))
            sD[i] = jac_add(jac_mul(G, Int(a), ell), jac_mul(T, Int(b), ell))
            sa[i] = a; sb[i] = b
        end
        sD, sa, sb
    end

    shared_lp1 = Dict{NTuple{2,Int}, Tuple{Dict{Int,Int}, Int, Int, Int}}()
    shared_lp1_lock = ReentrantLock()
    shared_lp2 = LP2Graph()
    shared_lp2_lock = ReentrantLock()
    shared_lp_doubled = Dict{NTuple{2,Int}, Tuple{Dict{Int,Int}, Int, Int}}()
    shared_lp1_conj = ShardedLP1Conj()
    shared_lp2_conj = LP2ConjGraph()
    shared_lp2_conj_lock = ReentrantLock()
    set_lp2_principal_check_context!(fb, G, T)
    ort = OnlineRankTracker(ell)

    # Single-threaded for simplicity here; swap in @sync/@spawn for full MT.
    p2_result = phase2_worker(
        G, T, fb, BigInt(ell), pt2idx,
        step_D, step_a, step_b,
        rel_counter, rel_target, 10_000_000,
        1, true,
        true, DEFAULT_MAX_LP2_NODES,
        true, DEFAULT_MAX_LP2_CONJ_NODES,
        p1_rows, p1_alpha, p1_beta,
        ort,
        shared_lp1, shared_lp1_lock,
        shared_lp2, shared_lp2_lock,
        shared_lp_doubled,
        shared_lp1_conj,
        shared_lp2_conj, shared_lp2_conj_lock,
        LPResidualCollector()
    )

    rel_rows  = vcat(p1_rows,  p2_result.rel_rows)
    alpha_vec = vcat(p1_alpha, p2_result.alpha_vec)
    beta_vec  = vcat(p1_beta,  p2_result.beta_vec)

    verbose && @printf("\nTotal relations: %d  (nF=%d)\n", length(rel_rows), nF)

    # Try cycle-union solve first.
    cu = cycle_union_solve(rel_rows, alpha_vec, beta_vec, nF, ell;
                           G=G, T=T, verbose=verbose)

    if cu.cycle_solver_succeeded
        @printf("cycle_union_solve succeeded: k=%d\n", cu.k)
        return cu.k
    end

    # Fallback: Gaussian elimination.
    verbose && println("cycle_union_solve did not find k; falling back to left_kernel_all.")
    kernels = left_kernel_all(rel_rows, nF, ell)
    nrel    = length(rel_rows)
    for γ in kernels
        Sa = mod(sum(BigInt(γ[i]) * alpha_vec[i] for i in eachindex(γ)), ell)
        Sb = mod(sum(BigInt(γ[i]) * beta_vec[i]  for i in eachindex(γ)), ell)
        Sb == 0 && continue
        k = mod(-Sa * powermod(Sb, ell - 2, ell), ell)
        jac_mul(G, k, ell) == T && return k
    end
    return nothing
end
