# =============================================================================
#  trial3_amortized.jl  —  Amortized DLP infrastructure
#
#  Two independent but complementary ideas:
#
#  1. ALPHA-ONLY PRECOMPUTATION  (amortize_alpha_phase)
#     ─────────────────────────────────────────────────
#     The insight: if we suppress β (set β=0 in every walk step during
#     precomputation), every relation has the form
#
#         FB-atoms  =  α·G                 (β-free)
#
#     Gaussian elim on this over-determined system gives us a dictionary
#
#         atom_log[pt]  =  log_G(pt)  ∈ Z/ell
#
#     for every factor-base atom.  This is the *precomputation* phase and
#     only needs to be done once for the group.
#
#     Then for a new target T, we collect a *single* β≠0 relation:
#
#         c₁·pt₁ + c₂·pt₂ + c₃·pt₃  =  α·G + β·T      (β≠0)
#
#     Substituting the known atom logs:
#
#         α + β·k  ≡  c₁·log[pt₁] + c₂·log[pt₂] + c₃·log[pt₃]  (mod ell)
#         k  =  (RHS − α) · β⁻¹  mod ell
#
#     This makes all subsequent DLPs O(polylog p) after the precomputation.
#
#     Why Lp3-suppression enables this:
#     With only Lp1 (and Lp2 spanning-tree) relations, every relation
#     involves at most 2 non-FB atoms, which close under the spanning tree.
#     The resulting matrix has H₂ = 0 (no independent 2-cycles in the
#     chain complex), so the atom-log map extends uniquely from the spanning
#     tree.  This is the algebraic reason β-free relations suffice to fix
#     all atom logs.
#
#  2. O(n) CYCLE-UNION LA SOLVER  (cycle_union_solve)
#     ─────────────────────────────────────────────────
#     Classical observation: if H₂ = 0, the relation matrix (over Z/ell)
#     viewed as the boundary map ∂₁ of a 1-complex has trivial second
#     homology.  The kernel of ∂₁ is generated by the *cycles* of the
#     factor-base graph.  Finding a kernel vector = finding a cycle.
#
#     Algorithm (union-find, O(n α(n))):
#       - Build a graph G on factor-base vertices.
#       - Each relation row is an (hyper)edge on its support.
#       - Process rows with a DSU.  When inserting a row creates a cycle,
#         that cycle is a kernel vector — read it off from the DSU path.
#       - Under H₂=0 every kernel vector arises this way.
#
#     The recovered kernel vectors satisfy:
#       γᵢ · rel_matrix = 0  over GF(ell)
#     and we solve  k = −(γ·α)(γ·β)⁻¹  as usual.
#
#     Complexity: O(n · α(n))  where n = |relations|,
#     vs O(n · m · min(n,m)) for dense Gaussian elimination.
#
#     NOTE: the H₂=0 hypothesis is *conjectural* for this walk.  The solver
#     falls back to left_kernel_all() if cycle extraction fails to produce a
#     valid k.  The flag `cycle_solver_succeeded` in the return value tells
#     you which path was taken.
#
# =============================================================================

# ---------------------------------------------------------------------------
#  DSU (Disjoint Set Union) with path compression and union-by-rank,
#  augmented to track the *path label* (sum of edge weights mod ell) needed
#  to reconstruct the cycle vector.
#
#  Label convention: label[v] is the value L such that
#      atom_log[v]  ≡  atom_log[root(v)] + L   (mod ell)
#  along the DSU tree path.  When two components are merged by edge (u,v,w):
#      atom_log[u]  +  w  ≡  atom_log[v]        (the relation says so)
#  so label[u] is set appropriately during union.
# ---------------------------------------------------------------------------
mutable struct LabelledDSU
    parent ::Vector{Int}
    rank   ::Vector{Int}
    label  ::Vector{Int}   # label[v] = offset from root, mod ell
    ell    ::Int
end

function LabelledDSU(n::Int, ell::Int)
    LabelledDSU(collect(1:n), zeros(Int, n), zeros(Int, n), ell)
end

# Find root of v; path-compress and accumulate label offset.
# Returns (root, label_v_to_root) where label_v_to_root satisfies
#     atom_log[v] ≡ atom_log[root] + label_v_to_root  (mod ell)
function dsu_find(d::LabelledDSU, v::Int)
    if d.parent[v] == v
        return v, 0
    end
    root, plabel = dsu_find(d, d.parent[v])
    # Path compress
    d.label[v]  = mod(d.label[v] + plabel, d.ell)
    d.parent[v] = root
    return root, d.label[v]
end

# Try to union components of u and v given the constraint:
#   coeff_u · atom_log[u]  +  coeff_v · atom_log[v]  ≡  rhs  (mod ell)
# Simplified to weight w: atom_log[u] - atom_log[v] ≡ w  (when coeff_u=1, coeff_v=-1).
#
# More generally we handle the binary case: the caller pre-computes w for us.
#
# Returns:
#   :merged   — components were distinct; merged successfully.
#   :cycle    — components were the same; cycle detected.  The cycle-weight
#               (= the residual mod ell that should be zero if the relation
#               is consistent) is returned as cycle_weight.
function dsu_union!(d::LabelledDSU, u::Int, v::Int, w::Int)
    ru, lu = dsu_find(d, u)
    rv, lv = dsu_find(d, v)

    if ru == rv
        # Cycle: the residual is  lu - lv - w  mod ell.
        cycle_weight = mod(lu - lv - w, d.ell)
        return :cycle, cycle_weight
    end

    # Merge smaller rank into larger.
    if d.rank[ru] < d.rank[rv]
        ru, rv = rv, ru
        lu, lv = lv, lu
        w = mod(-w, d.ell)
    end
    # Now ru is the new root.
    # We need label[rv] such that atom_log[rv] ≡ atom_log[ru] + label[rv].
    # From atom_log[u] - atom_log[v] ≡ w and lu,lv:
    #   atom_log[u] = atom_log[ru] + lu
    #   atom_log[v] = atom_log[rv_new_root=ru] + label[rv]
    #   (atom_log[ru] + lu) - (atom_log[ru] + label[rv]) ≡ w
    #   label[rv] ≡ lu - w  (mod ell)  ... but rv's root was rv, so adjust for lv:
    #   atom_log[rv_old] ≡ atom_log[ru] + label[rv_old]
    #   atom_log[v]      = atom_log[rv_old] + lv  ≡  atom_log[ru] + label[rv_old] + lv
    #   atom_log[u]      = atom_log[ru] + lu
    #   lu - (label[rv_old] + lv) ≡ w  →  label[rv_old] = lu - lv - w
    d.label[rv]  = mod(lu - lv - w, d.ell)
    d.parent[rv] = ru
    d.rank[ru] == d.rank[rv] && (d.rank[ru] += 1)
    return :merged, 0
end

# ---------------------------------------------------------------------------
#  cycle_union_solve
#
#  O(n · α(n)) kernel / atom-log solver under the H₂=0 hypothesis.
#
#  The key insight: every phi-walk relation has exactly weight 3 (atoms P0, R, S).
#  The relation is:
#
#       log[P0] + log[R] + log[S]  ≡  α + β·k   (mod ell)
#
#  This is a *ternary* hyperedge on the factor-base graph.  We handle it by
#  building a spanning tree of the factor-base graph via iterative reduction:
#
#    - Maintain a DSU with labels: label[v] = log[v] - log[root(v)]  (mod ell).
#    - Each ternary row (u, v, w) has rhs = α_i + β_i·k (unknown k).
#      We track it as:  log[u] + log[v] + log[w] = rhs_i  (with rhs_i partially
#      unknown due to k, but we treat rhs_i as a symbolic affine function of k).
#    - Instead of carrying k symbolically, we use the following trick:
#
#      Once the DSU has placed two of the three atoms in the same component
#      (their logs are known relative to the root), the third atom's log is
#      determined up to the root's unknown.  When a relation closes a cycle
#      (all three atoms already in the same component), we get a constraint
#      on α + β·k and can solve for k.
#
#  Concretely:
#    log[u] = label[u] + log[root_u]     (from DSU)
#    log[v] = label[v] + log[root_v]
#    log[w] = label[w] + log[root_w]
#
#  Case A: root_u = root_v = root_w  (full cycle)
#    label[u] + label[v] + label[w] + log[root] · (coeff_u + coeff_v + coeff_w)
#        ≡ α_i + β_i·k
#    With unit coefficients (all +1):
#    (label[u] + label[v] + label[w]) + 3·log[root] ≡ α_i + β_i·k
#    But log[root] is unknown unless pinned.  So we maintain per-component a
#    symbolic "root log" variable R_c ∈ Z/ell, and when two components merge
#    we eliminate one variable.
#
#  This becomes exactly sparse Gaussian elimination, just structured so that
#  under H₂=0 the component-graph is a forest and we process it in O(n).
#
#  Implementation: we use a two-level approach:
#    Level 1 – DSU on factor-base atoms (nF vertices), labelled with
#              log[v] - log[root(v)].
#    Level 2 – "component log" system: one unknown per DSU component.
#              Each relation, once reduced to component-log variables, gives
#              one linear equation.  Under H₂=0 and unit coefficients this
#              system is sparse (weight ≤ 3) and acyclic (tree), so it
#              resolves greedily in O(n).
#
#  In the weight-3 / all-coefficients-+1 case (which is what the phi walk
#  produces), the component-log system is itself a 3-uniform hypergraph, and
#  we apply the same iterative reduction to it.
#
#  Returns NamedTuple:
#    k                      — Int or nothing
#    atom_logs              — Vector{Int} or nothing
#    cycle_solver_succeeded — Bool
#    n_cycles_found         — Int
#    n_deferred_resolved    — Int
# ---------------------------------------------------------------------------
function cycle_union_solve(rel_rows   ::Vector{Dict{Int,Int}},
                           alpha_vec  ::Vector{BigInt},
                           beta_vec   ::Vector{BigInt},
                           nF         ::Int,
                           ell        ::Int;
                           G          ::Union{Nothing,Div2} = nothing,
                           T          ::Union{Nothing,Div2} = nothing,
                           verbose    ::Bool = true)

    m = length(rel_rows)
    m == 0 && return (k=nothing, atom_logs=nothing,
                      cycle_solver_succeeded=false, n_cycles_found=0,
                      n_deferred_resolved=0)

    # ------------------------------------------------------------------
    #  Fast path: same-support pairs.
    #
    #  The observed early-solve case is a kernel vector with support size 2:
    #  two rows r1, r2 that share identical column support {a,b,c} with the
    #  same coefficients.  Their combination γ = (β_r2, -β_r1) satisfies:
    #
    #    γ·rel  = β_r2·row_r1 - β_r1·row_r2
    #           = (β_r2 - β_r1)·[a+b+c cols]  (cancels iff same support+coeffs)
    #
    #  More generally: two rows with the same normalised support give a
    #  kernel vector immediately.  We check this in O(n) with a hash map
    #  keyed on (sorted columns, normalised coefficients).
    #
    #  For each such pair (r1, r2), the combination is:
    #    Sa = β_r2·α_r1 - β_r1·α_r2   (mod ell)
    #    Sb = β_r2·β_r1 - β_r1·β_r2  = 0  ← that's Sb=0, no good
    #
    #  Wait — if the columns cancel entirely we need Sb ≠ 0, so the rows
    #  must NOT be identical on the β side.  The actual kernel structure is:
    #
    #    row_r1: cols C, α_r1·G + β_r1·T  →  sum_C log[c] = α_r1 + β_r1·k
    #    row_r2: cols C, α_r2·G + β_r2·T  →  sum_C log[c] = α_r2 + β_r2·k
    #
    #  Subtracting:  0 = (α_r1 - α_r2) + (β_r1 - β_r2)·k
    #                k = (α_r2 - α_r1)·(β_r1 - β_r2)^{-1}  mod ell
    #
    #  This works whenever β_r1 ≠ β_r2.  No DSU needed at all.
    # ------------------------------------------------------------------
    # Build canonical support key: sorted vector of (col, coeff mod ell) pairs.
    support_key(row) = sort!([(j, mod(v, ell)) for (j,v) in row if mod(v,ell) != 0])
    # Map key → (row_index, α, β) of first row seen with this support.
    support_map = Dict{Vector{Tuple{Int,Int}}, Tuple{Int,BigInt,BigInt}}()

    n_same_support = 0
    k_candidate    = nothing

    function verify_k(k::Int)
        G === nothing && return true
        jac_mul(G, k, ell) == T
    end

    for ri in 1:m
        key = support_key(rel_rows[ri])
        isempty(key) && continue
        ai  = alpha_vec[ri]
        bi  = beta_vec[ri]

        if haskey(support_map, key)
            rj, aj, bj = support_map[key]
            # rows ri and rj have identical support+coeffs.
            # k = (aj - ai) * (bi - bj)^{-1}  mod ell
            Δβ = mod(Int(bi) - Int(bj), ell)
            if Δβ != 0
                Δα  = mod(Int(aj) - Int(ai), ell)
                k_try = mod(Δα * powermod(Δβ, ell - 2, ell), ell)
                n_same_support += 1
                if verify_k(k_try)
                    k_candidate = k_try
                    verbose && @printf("[cycle_union] same-support pair (rows %d,%d) → k=%d ✓\n",
                                       ri, rj, k_candidate)
                    # Return immediately — this is O(1) once found.
                    return (k                      = k_candidate,
                            atom_logs              = nothing,
                            cycle_solver_succeeded = true,
                            n_cycles_found         = 1,
                            n_deferred_resolved    = 0)
                end
            end
            # Δβ=0 means same β too → trivially dependent, skip.
        else
            support_map[key] = (ri, ai, bi)
        end
    end

    verbose && n_same_support > 0 &&
        @printf("[cycle_union] %d same-support pairs found but none gave valid k\n", n_same_support)

    # ------------------------------------------------------------------
    #  Work-queue peeling solver (handles deeper kernel structure).
    # ------------------------------------------------------------------
    # ------------------------------------------------------------------
    #  Level-1 DSU: track atom-log offsets from component roots.
    #  label[v]  =  log[v] - log[root(v)]   mod ell
    #  When log[root(v)] is known (pinned), log[v] = label[v] + log[root].
    # ------------------------------------------------------------------
    dsu        = LabelledDSU(nF, ell)
    root_log   = fill(-1, nF)   # root_log[r] = known log of root r; -1 = unknown
    # atom_log[v] = known absolute log of v; -1 = unknown
    atom_log   = fill(-1, nF)

    # Pin root r's log to val, propagate to all atoms in its component.
    function pin_root!(r::Int, val::Int)
        root_log[r] = mod(val, ell)
        # Propagate to all atoms whose find() == r.
        # (Lazy: we'll recompute atom_log on demand via dsu_find.)
    end

    # Get atom log if known, else -1.
    function get_atom_log(v::Int)::Int
        r, lv = dsu_find(dsu, v)
        rl = root_log[r]
        rl == -1 && return -1
        return mod(lv + rl, ell)
    end

    # Attempt to solve a binary relation once at least one side is pinned.
    #
    # IMPORTANT: we do *not* fake a DSU union here.  A zero-weight union would
    # assert log[u] ≡ log[v], which is generally false and silently corrupts
    # labels.  If neither side is pinned yet, we simply defer the row.
    #
    # Returns:
    #   :pinned    — a new root log was recovered and pinned
    #   :cycle     — both atoms were already in the same component
    #   :deferred  — not enough information yet
    function merge_binary!(u::Int, cu::Int, v::Int, cv::Int, rhs::Int)
        ru, lu = dsu_find(dsu, u)
        rv, lv = dsu_find(dsu, v)

        if ru == rv
            return :cycle
        end

        # If the u-side component is pinned, solve for v.
        if root_log[ru] != -1
            cv_mod = mod(cv, ell)
            cv_mod == 0 && return :deferred
            log_u  = mod(lu + root_log[ru], ell)
            log_v  = mod((rhs - cu * log_u) * powermod(cv_mod, ell - 2, ell), ell)
            r_v, l_v = dsu_find(dsu, v)
            pin_root!(r_v, mod(log_v - l_v, ell))
            return :pinned
        end

        # Otherwise, if the v-side component is pinned, solve for u.
        if root_log[rv] != -1
            cu_mod = mod(cu, ell)
            cu_mod == 0 && return :deferred
            log_v  = mod(lv + root_log[rv], ell)
            log_u  = mod((rhs - cv * log_v) * powermod(cu_mod, ell - 2, ell), ell)
            r_u, l_u = dsu_find(dsu, u)
            pin_root!(r_u, mod(log_u - l_u, ell))
            return :pinned
        end

        return :deferred
    end

    # ------------------------------------------------------------------
    #  Process all relations in a work-queue loop.
    #  Each relation is processed when enough of its atoms are resolved
    #  to determine at least one new atom or detect a cycle (→ solve k).
    # ------------------------------------------------------------------
    n_cycles           = 0
    n_deferred_resolved = 0
    k_candidate        = nothing

    # Work queue: indices of unresolved relations.
    pending   = collect(1:m)
    n_passes  = 0
    max_passes = m + 2   # safety cap; under H₂=0 should terminate in ≤ n passes

    while !isempty(pending) && n_passes < max_passes
        n_passes += 1
        next_pending = Int[]
        made_progress = false

        for ri in pending
            row     = rel_rows[ri]
            support = [(j, mod(v, ell)) for (j, v) in row if mod(v, ell) != 0 && 1 <= j <= nF]
            isempty(support) && continue

            # Compute known-log contribution and collect unknown atoms.
            rhs_known    = mod(Int(alpha_vec[ri]) + Int(beta_vec[ri]), ell)
            # (α + β absorbed into rhs; k is implicitly 0 for tree-building,
            #  and we solve for k when a cycle closes.)
            # Actually: rhs = α_i (pretend k=1 for tree; correct at cycle close).
            # We track everything symbolically as:
            #   sum_j  coeff_j * log[j]  ≡  alpha_i + beta_i * k
            # and at cycle-close we have all logs known → solve for k.

            known_sum  = 0
            unknown    = Tuple{Int,Int}[]   # (atom_idx, coeff)
            for (j, cj) in support
                lj = get_atom_log(j)
                if lj != -1
                    known_sum = mod(known_sum + cj * lj, ell)
                else
                    push!(unknown, (j, cj))
                end
            end

            n_unk = length(unknown)

            if n_unk == 0
                # Cycle: all atoms known.  Check consistency → solve for k.
                n_cycles += 1
                # known_sum ≡ alpha_i + beta_i * k
                # k = (known_sum - alpha_i) * beta_i^{-1}
                ai = mod(Int(alpha_vec[ri]), ell)
                bi = mod(Int(beta_vec[ri]),  ell)
                if bi != 0
                    k_try = mod((known_sum - ai) * powermod(bi, ell - 2, ell), ell)
                    if G !== nothing && T !== nothing
                        if jac_mul(G, k_try, ell) == T
                            k_candidate = k_try
                            verbose && @printf("[cycle_union] Cycle at row %d → k=%d ✓\n", ri, k_candidate)
                        end
                    else
                        k_candidate === nothing && (k_candidate = k_try)
                    end
                end
                made_progress = true

            elseif n_unk == 1
                # One unknown: pin it.
                j_unk, cj = unknown[1]
                ai  = mod(Int(alpha_vec[ri]), ell)
                bi  = mod(Int(beta_vec[ri]),  ell)
                # known_sum + cj*log[j_unk] ≡ ai + bi*k
                # We don't know k, so we can only pin if bi==0 (α-only relation).
                # If bi != 0, defer until k is known.
                if bi == 0
                    cj_inv   = powermod(cj, ell - 2, ell)
                    log_j    = mod((ai - known_sum) * cj_inv, ell)
                    r_j, lj  = dsu_find(dsu, j_unk)
                    pin_root!(r_j, mod(log_j - lj, ell))
                    made_progress = true
                    n_deferred_resolved += 1
                elseif k_candidate !== nothing
                    # k is now known; resolve immediately.
                    rhs_full = mod(ai + bi * k_candidate, ell)
                    cj_inv   = powermod(cj, ell - 2, ell)
                    log_j    = mod((rhs_full - known_sum) * cj_inv, ell)
                    r_j, lj  = dsu_find(dsu, j_unk)
                    pin_root!(r_j, mod(log_j - lj, ell))
                    made_progress = true
                    n_deferred_resolved += 1
                else
                    push!(next_pending, ri)
                end

            elseif n_unk == 2
                # Two unknowns: gives a binary DSU edge (modulo k being unknown).
                # We can at least merge the two components structurally.
                # If one component root is pinned and k is known (or bi==0), we
                # can also pin the other.
                (j1, c1), (j2, c2) = unknown[1], unknown[2]
                ai = mod(Int(alpha_vec[ri]), ell)
                bi = mod(Int(beta_vec[ri]),  ell)
                rhs_effective = bi == 0 ? mod(ai - known_sum, ell) :
                                k_candidate !== nothing ?
                                    mod(ai + bi * k_candidate - known_sum, ell) : -1

                if rhs_effective != -1
                    status = merge_binary!(j1, c1, j2, c2, rhs_effective)
                    if status == :cycle
                        n_cycles += 1
                        made_progress = true
                    elseif status == :pinned
                        n_deferred_resolved += 1
                        made_progress = true
                    else
                        push!(next_pending, ri)
                    end
                else
                    # No safe structural action yet; revisit once k is known
                    # or another row pins one of the components.
                    push!(next_pending, ri)
                end

            else
                # Three or more unknowns: defer.
                push!(next_pending, ri)
            end
        end

        pending = next_pending
        !made_progress && break
    end

    # Build atom_logs from DSU + root_log.
    atom_logs = nothing
    try
        logs = Vector{Int}(undef, nF)
        for v in 1:nF
            logs[v] = get_atom_log(v)
        end
        atom_logs = logs
    catch
    end

    if verbose
        n_pinned = count(v -> get_atom_log(v) != -1, 1:nF)
        @printf("[cycle_union] %d cycles found, %d deferred resolved, %d/%d atoms pinned, k=%s\n",
                n_cycles, n_deferred_resolved, n_pinned, nF,
                k_candidate === nothing ? "nothing" : string(k_candidate))
    end

    return (k                      = k_candidate,
            atom_logs              = atom_logs,
            cycle_solver_succeeded = k_candidate !== nothing,
            n_cycles_found         = n_cycles,
            n_deferred_resolved    = n_deferred_resolved)
end

# ---------------------------------------------------------------------------
#  chain_path_solve
#
#  O(nF + m_lp) kernel solver that exploits the phase-1 chain structure.
#
#  BACKGROUND
#  ──────────
#  Phase-1 builds the factor base by chaining: each row i has the form
#
#      {anchor_i,  anchor_{i+1},  S_i}    with RHS  α_i + β_i·k
#
#  where the *next* anchor is always R (the left residual from phi_residual),
#  and S_i is the pendant ("right residual").  Consecutive rows share exactly
#  one atom (anchor_{i+1}).  This makes the phase-1 incidence graph a *path*
#  on the anchor atoms, with pendant S-atoms attached to each edge.
#
#  SYMBOLIC LOG PROPAGATION
#  ────────────────────────
#  Fix L₀ = log[anchor_0] as a free variable.  Define for each chain atom v:
#
#      log[v]  ≡  Av + Bv·k + L₀   (mod ell)
#
#  where Av, Bv are integers computed from cumulative chain sums, and the
#  implicit coefficient of L₀ is 1 for every atom reachable from anchor_0.
#  (For atoms not on the phase-1 chain we leave them symbolically unresolved
#  and fall back to Gaussian elimination for those rows.)
#
#  Along the chain, starting from anchor_0:
#    Row 0:  log[anchor_0] + log[anchor_1] + log[S_0] = α_0 + β_0·k
#            ⟹  (L₀) + (A_{a1} + B_{a1}·k + L₀) + (A_{S0} + B_{S0}·k + L₀)
#                = α_0 + β_0·k
#
#  But we have 3 unknowns in row 0 (anchor_0, anchor_1, S_0) and only 1
#  equation, so we can't immediately pin everyone.  The trick is to treat
#  the system as a 2D linear system over the pair (L₀, k):
#
#    For each atom v, represent its log as  log[v] = Av + Bv·k + Cv·L₀
#    with initial assignments:
#      anchor_0:  A=0, B=0, C=1   (log = L₀)
#      everyone else: unknown (C=0, A=0, B=0 until assigned)
#
#  Process chain rows left-to-right.  Row i has atoms {anchor_i, anchor_{i+1}, S_i}.
#  After processing row i-1, anchor_i is assigned.  Row i then gives:
#
#    (A_ai + B_ai·k + C_ai·L₀)
#  + (A_{ai+1} + B_{ai+1}·k + C_{ai+1}·L₀)
#  + (A_{Si} + B_{Si}·k + C_{Si}·L₀)
#  = α_i + β_i·k
#
#  This is an equation over (L₀, k).  If exactly one of {anchor_{i+1}, S_i}
#  is unassigned, we can express it directly.  After processing all chain rows
#  in a single forward pass, we've assigned every chain atom a (A,B,C) triple.
#
#  LP-CLOSURE ROWS → EQUATIONS IN (L₀, k)
#  ─────────────────────────────────────────
#  Any phase-2 LP-closure row that involves only chain-assigned atoms gives:
#
#    Σ_j coeff_j · (A_j + B_j·k + C_j·L₀) = α_lp + β_lp·k
#    ⟹  (Σ coeff_j·A_j - α_lp) + (Σ coeff_j·B_j - β_lp)·k
#        + (Σ coeff_j·C_j)·L₀ = 0
#    ⟹  P + Q·k + R·L₀ = 0   (one linear equation in two unknowns)
#
#  Two such LP-closure rows with (P₁,Q₁,R₁) and (P₂,Q₂,R₂) give a 2×2 system:
#
#    [Q₁  R₁] [k ]   [-P₁]
#    [Q₂  R₂] [L₀] = [-P₂]
#
#  Solve via Cramer's rule mod ell.  If the determinant Q₁R₂ - Q₂R₁ ≠ 0, we
#  get unique k.
#
#  FALLBACK
#  ────────
#  If chain propagation stalls (because a chain row has >1 unresolved atom
#  even after the forward pass), or if no LP-closure equation pair solves for k,
#  the function returns (k=nothing, succeeded=false) and the caller falls back
#  to Gaussian elimination.
#
#  The n_phase1 parameter tells us how many of rel_rows[1:n_phase1] are the
#  ordered phase-1 chain rows.  rel_rows[n_phase1+1:end] are phase-2 rows.
#
#  Returns NamedTuple with same shape as cycle_union_solve.
# ---------------------------------------------------------------------------
function chain_path_solve(rel_rows   ::Vector{Dict{Int,Int}},
                          alpha_vec  ::Vector{BigInt},
                          beta_vec   ::Vector{BigInt},
                          nF         ::Int,
                          ell        ::Int,
                          n_phase1   ::Int;
                          G          ::Union{Nothing,Div2} = nothing,
                          T          ::Union{Nothing,Div2} = nothing,
                          verbose    ::Bool = true)

    m = length(rel_rows)
    (m == 0 || n_phase1 == 0) && return (k=nothing, atom_logs=nothing,
                                          chain_path_succeeded=false,
                                          n_equations=0)

    # ── Symbolic log representation ───────────────────────────────────────────
    #
    # Each atom v gets a triple (Av, Bv, Cv) meaning:
    #     log[v]  ≡  Av + Bv·k + Cv·L₀   (mod ell)
    # where L₀ = log[anchor_0] is a free scalar and k is the DLP target.
    #
    # We start with anchor_0 → (0, 0, 1).  We propagate assignments using
    # the relation rows.  When all atoms in a row are assigned, we collect
    # a linear constraint   P + Q·k + R·L₀ ≡ 0  (mod ell).
    # Two such independent constraints solve the 2×2 system for k and L₀.
    #
    # KEY FIX vs original: handle the 2-unknown case in chain rows by using
    # a second free variable.  We introduce a "relative" representation:
    # when a chain row has anchor_i assigned and {anchor_{i+1}, S_i} both
    # unknown, we:
    #   (a) Assign anchor_{i+1} → (0, 0, 0, 1) with a NEW free variable L_j
    #       (the j-th free anchor log beyond L₀).
    #   (b) Assign S_i in terms of (anchor_i, anchor_{i+1}, rhs).
    #
    # This gives each atom a 4-tuple (Av, Bv, Cv, Dv) where Dv is the
    # coefficient of L_j, the free variable introduced at chain step j.
    # When anchor_{i+1} gets pinned later (from an LP-closure row making
    # it n_unk==1), we substitute and reduce all downstream atoms.
    #
    # Rather than implementing this full symbolic algebra, we use a simpler
    # equivalent: a sparse augmented-matrix representation.  Each atom's log
    # is a linear combination of [k, L₀, L_1, L_2, ...] where L_0=log[anchor_0]
    # and L_j are free anchor logs introduced per chain segment.
    #
    # We maintain: for each atom v, a sparse vector coeffs[v] (length = 1 + 1 +
    # n_free_introduced) plus a constant term const[v], such that:
    #     log[v] = const[v] + coeffs_k[v]·k + Σ_j coeffs_free[v][j]·L_j
    #
    # When two atoms in the same equation are linked through the free variable
    # system and all atoms are expressed in terms of the same free variables,
    # the constraint becomes a linear equation in those free variables + k.
    # We collect these and solve.
    #
    # IMPLEMENTATION: to keep it simple, we cap the number of free variables
    # at 2 (k and L₀).  Any chain segment that can't be expressed with these
    # two is left unresolved and falls through to Gaussian elim.  In practice,
    # the LP-closure rows (weight 2) quickly pin anchor atoms and allow the
    # rest of the chain to resolve.

    # ── Step 1: Identify phase-1 chain topology ───────────────────────────────
    # anchor_seq[i] = the anchor atom at chain position i (0-indexed).
    # We extract this from the row structure: each consecutive pair of phase-1
    # rows shares exactly one atom (the "next anchor" = R in the walk).
    #
    # Phase-1 walk does:  cur_pt = R  after each step, and the row is {cur, R, S}.
    # So row i: {anchor_i, anchor_{i+1}, S_i}  where anchor_{i+1} is the shared
    # atom between row i and row i+1.
    #
    # Build atom_to_chain_pos: atom → chain position (anchor sequence index).
    # Also build chain_S: chain_S[i] = the pendant (S) atom of row i.

    # Get distinct atom sets for each phase-1 row.
    p1_atoms = Vector{Vector{Int}}(undef, n_phase1)
    for i in 1:n_phase1
        p1_atoms[i] = [j for (j, v) in rel_rows[i] if mod(v, ell) != 0 && 1 <= j <= nF]
    end

    # Identify chain anchor sequence by mutual overlap between consecutive rows.
    anchor_seq = Int[]    # anchor_seq[i] = anchor at position i-1 (1-indexed)
    chain_S    = Int[]    # chain_S[i] = pendant atom of chain row i

    # Row 1: find which atom is shared with row 2.
    if n_phase1 >= 2
        set1 = Set(p1_atoms[1])
        set2 = Set(p1_atoms[2])
        shared_12 = intersect(set1, set2)
        if isempty(shared_12)
            verbose && @printf("[chain_path] rows 1-2 share no atom; chain not detected\n")
            return (k=nothing, atom_logs=nothing, chain_path_succeeded=false, n_equations=0)
        end
        anchor1 = first(shared_12)   # anchor at position 1 (= anchor_{1} in 0-indexed)
        # anchor_0 = the atom in row 1 that is NOT anchor1 and NOT the S atom.
        non_anchor1 = [a for a in p1_atoms[1] if a != anchor1]
        anchor0 = isempty(non_anchor1) ? anchor1 : non_anchor1[1]
        S0      = length(non_anchor1) >= 2 ? non_anchor1[2] : anchor1
        push!(anchor_seq, anchor0, anchor1)
        push!(chain_S, S0)
        # Rows 2..n_phase1: anchor_{i} is already in anchor_seq; find anchor_{i+1} and S_i.
        for i in 2:n_phase1
            cur_anchor = anchor_seq[end]
            atoms_i    = p1_atoms[i]
            rest       = [a for a in atoms_i if a != cur_anchor]
            if isempty(rest)
                push!(chain_S, cur_anchor)   # degenerate
                push!(anchor_seq, cur_anchor)
                continue
            end
            # Find next anchor: atom in row i that also appears in row i+1 (if exists).
            if i < n_phase1
                set_next = Set(p1_atoms[i+1])
                shared = [a for a in rest if a in set_next]
                if !isempty(shared)
                    next_anchor = shared[1]
                    s_i = first(a for a in rest if a != next_anchor)
                else
                    next_anchor = rest[1]
                    s_i = length(rest) >= 2 ? rest[2] : rest[1]
                end
            else
                next_anchor = rest[1]
                s_i = length(rest) >= 2 ? rest[2] : rest[1]
            end
            push!(anchor_seq, next_anchor)
            push!(chain_S, s_i)
        end
    elseif n_phase1 == 1
        atoms1 = p1_atoms[1]
        length(atoms1) < 2 && return (k=nothing, atom_logs=nothing, chain_path_succeeded=false, n_equations=0)
        push!(anchor_seq, atoms1[1], atoms1[2])
        push!(chain_S, length(atoms1) >= 3 ? atoms1[3] : atoms1[1])
    else
        return (k=nothing, atom_logs=nothing, chain_path_succeeded=false, n_equations=0)
    end

    # ── Step 2: Symbolic assignment using 4-component vectors ────────────────
    #
    # Represent each atom's log as a linear combination of basis elements:
    #   basis[1] = k        (the DLP secret)
    #   basis[2] = L₀       (log of anchor_0, free)
    #   basis[3..] = L_j    (log of anchor_j introduced when that anchor is
    #                         unresolved at the time of a chain row)
    #
    # coeffs[v] = sparse Dict{Int,Int}: basis_index → coefficient mod ell
    # const_v[v] = constant term mod ell
    # assigned[v] = true once log[v] is fully expressed.

    # We keep the basis size bounded.  In practice we introduce at most one
    # free variable per "gap" in the chain (when an LP closure doesn't come
    # early enough).  Bound: at most n_phase1 + 2 basis elements.
    MAX_BASIS = n_phase1 + 4

    const_v  = zeros(Int, nF)
    coeffs   = [Dict{Int,Int}() for _ in 1:nF]   # basis_idx → coeff
    assigned = falses(nF)
    n_basis  = 2   # initially: basis[1]=k, basis[2]=L₀

    # basis_atom[j] = atom index whose free variable is basis element j (for j>=2)
    basis_atom = fill(-1, MAX_BASIS)
    basis_atom[2] = anchor_seq[1]   # L₀ = log[anchor_0]

    function assign!(v::Int, c::Int, cs::Dict{Int,Int})
        const_v[v] = mod(c, ell)
        coeffs[v]  = Dict{Int,Int}(k => mod(cv, ell) for (k, cv) in cs if mod(cv, ell) != 0)
        assigned[v] = true
    end

    # Introduce a new free basis element for atom `v` (unresolvable anchor).
    function introduce_free!(v::Int)::Int
        n_basis + 1 > MAX_BASIS && return -1
        n_basis += 1
        basis_atom[n_basis] = v
        assign!(v, 0, Dict{Int,Int}(n_basis => 1))
        return n_basis
    end

    # Assign anchor_0 as basis element 2 (L₀).
    assign!(anchor_seq[1], 0, Dict{Int,Int}(2 => 1))

    # ── Symbolic arithmetic helpers ───────────────────────────────────────────

    # Add two symbolic expressions (c1, cs1) + coeff*(c2, cs2), return new (c, cs).
    function sym_add(c1::Int, cs1::Dict{Int,Int}, coeff::Int, c2::Int, cs2::Dict{Int,Int})
        c  = Int(mod(Int128(c1) + Int128(coeff) * c2, ell))
        cs = copy(cs1)
        for (bi, cv) in cs2
            nv = Int(mod(Int128(get(cs, bi, 0)) + Int128(coeff) * cv, ell))
            nv == 0 ? delete!(cs, bi) : (cs[bi] = nv)
        end
        return c, cs
    end

    # Scale (c, cs) by scalar s.
    function sym_scale(s::Int, c::Int, cs::Dict{Int,Int})
        c2  = Int(mod(Int128(s) * c, ell))
        cs2 = Dict{Int,Int}()
        for (bi, cv) in cs
            nv = Int(mod(Int128(s) * cv, ell))
            nv != 0 && (cs2[bi] = nv)
        end
        return c2, cs2
    end

    # Given a row equation  Σ_j cj·log[j] = αi + βi·k
    # with some atoms assigned, try to assign one more unknown,
    # or collect a (P + Q·k + R·L₀) constraint.
    #
    # Returns :assigned, :constraint, :deferred_free, :deferred_many
    constraints_linear = Vector{Tuple{Int, Dict{Int,Int}}}()  # (P, coeffs_of_bases) s.t. P + Σ c_b·L_b = 0

    function process_row!(row::Dict{Int,Int}, αi::BigInt, βi::BigInt)
        support = [(j, mod(v, ell)) for (j, v) in row if mod(v, ell) != 0 && 1 <= j <= nF]
        isempty(support) && return :skip

        # Accumulate known part.
        sum_c  = 0
        sum_cs = Dict{Int,Int}()
        unknowns = Tuple{Int,Int}[]

        for (j, cj) in support
            if assigned[j]
                sum_c, sum_cs = sym_add(sum_c, sum_cs, cj, const_v[j], coeffs[j])
            else
                push!(unknowns, (j, cj))
            end
        end

        ai_mod = mod(Int(αi), ell)
        bi_mod = mod(Int(βi), ell)
        n_unk  = length(unknowns)

        # RHS as symbolic expression: αi + βi·k = ai_mod + (bi_mod)·k
        # Constraint form: sum_c + sum_cs·bases - ai_mod - bi_mod·k = Σ_j cj·log[j_unk]
        # Rewrite: Σ_j cj·log[j_unk] = (ai_mod - sum_c) + (bi_mod)·k - sum_cs·bases

        if n_unk == 0
            # Full constraint: sum_c + sum_cs·bases ≡ ai_mod + bi_mod·k
            # ⟹  (sum_c - ai_mod) + (get(sum_cs,1,0) - bi_mod)·k + Σ_{b≥2} sum_cs[b]·L_b = 0
            P    = mod(sum_c - ai_mod, ell)
            cmap = copy(sum_cs)
            cmap[1] = mod(get(cmap, 1, 0) - bi_mod, ell)
            cmap[1] == 0 && delete!(cmap, 1)
            push!(constraints_linear, (P, cmap))
            return :constraint

        elseif n_unk == 1
            # Assign: cj·log[j] = (ai_mod - sum_c) + (bi_mod - get(sum_cs,1,0))·k
            #                     - Σ_{b≥2} sum_cs[b]·L_b
            j, cj = unknowns[1]
            cj_inv = powermod(cj, ell - 2, ell)
            rhs_c  = mod(ai_mod - sum_c, ell)
            rhs_cs = Dict{Int,Int}(b => mod(-cv, ell) for (b, cv) in sum_cs)
            rhs_cs[1] = mod(get(rhs_cs, 1, 0) + bi_mod, ell)
            rhs_cs[1] == 0 && delete!(rhs_cs, 1)
            new_c, new_cs = sym_scale(cj_inv, rhs_c, rhs_cs)
            assign!(j, new_c, new_cs)
            return :assigned

        elseif n_unk == 2
            # Two unknowns: can we introduce a free variable for one?
            # Only do this for chain rows where one unknown is the "next anchor"
            # (it will appear in subsequent rows).
            # We introduce it as a new basis element if we have space.
            j1, c1 = unknowns[1]
            j2, c2 = unknowns[2]

            # Assign j2 in terms of j1 as a new free basis element.
            if n_basis < MAX_BASIS - 1
                idx = introduce_free!(j1)
                idx == -1 && return :deferred_many
                # Now j1 is assigned; retry this row.
                # j2: c2·log[j2] = (ai_mod - sum_c - c1·log[j1]) + bi_mod·k - sum_cs·bases
                rhs_c, rhs_cs = sym_add(ai_mod - sum_c, Dict{Int,Int}(b => mod(-cv, ell) for (b,cv) in sum_cs),
                                         -c1, const_v[j1], coeffs[j1])
                rhs_cs[1] = mod(get(rhs_cs, 1, 0) + bi_mod, ell)
                rhs_cs[1] == 0 && delete!(rhs_cs, 1)
                c2_inv = powermod(c2, ell - 2, ell)
                new_c, new_cs = sym_scale(c2_inv, rhs_c, rhs_cs)
                assign!(j2, new_c, new_cs)
                return :assigned
            else
                return :deferred_many
            end

        else
            return :deferred_many
        end
    end

    # ── Step 3: Forward pass over chain rows, then all rows iteratively ───────

    # First pass: chain rows in order.
    for i in 1:n_phase1
        process_row!(rel_rows[i], alpha_vec[i], beta_vec[i])
    end

    # Iterative passes over ALL rows until no progress.
    changed = true
    passes  = 0
    max_passes = 6
    while changed && passes < max_passes
        changed = false
        passes += 1
        for ri in 1:m
            result = process_row!(rel_rows[ri], alpha_vec[ri], beta_vec[ri])
            result == :assigned && (changed = true)
        end
    end

    n_assigned = count(identity, assigned)

    # ── Step 4: Extract and solve the linear system ───────────────────────────
    #
    # Each constraint is:  P + Σ_b c_b · L_b = 0  (mod ell)
    # where L_1 = k, L_2 = log[anchor_0], L_3... = additional free anchors.
    #
    # We want to solve for k (= L_1).  Eliminate non-k variables by collecting
    # equations as rows of a matrix and running light Gaussian elimination.

    n_eq  = length(constraints_linear)
    n_var = n_basis   # L_1..L_{n_basis}

    k_candidate = nothing

    function verify_k(k_try::Int)::Bool
        G === nothing && return true
        return jac_mul(G, k_try, ell) == T
    end

    if n_eq >= 1 && n_var <= n_eq + 2
        # Build augmented matrix [coeffs | -P] for variables L_1..L_{n_var}.
        # Row i: Σ_b coeff[i][b] · L_b = -P_i
        mat = zeros(Int, n_eq, n_var + 1)
        for (i, (P, cmap)) in enumerate(constraints_linear)
            mat[i, n_var + 1] = mod(-P, ell)   # RHS
            for (b, cv) in cmap
                1 <= b <= n_var || continue
                mat[i, b] = mod(cv, ell)
            end
        end

        # Gaussian elimination to get k from column 1.
        # Simple partial-pivot elimination mod ell.
        pivot_row = fill(0, n_var)   # pivot_row[b] = row index where basis b is pivot
        cur_row = 1
        for col in 1:n_var
            # Find pivot.
            piv = 0
            for r in cur_row:n_eq
                mat[r, col] != 0 && (piv = r; break)
            end
            piv == 0 && continue
            piv != cur_row && (mat[[cur_row, piv], :] = mat[[piv, cur_row], :])
            pivot_row[col] = cur_row

            inv_v = powermod(mat[cur_row, col], ell - 2, ell)
            for c in 1:(n_var + 1)
                mat[cur_row, c] = Int(mod(Int128(mat[cur_row, c]) * inv_v, ell))
            end
            for r in 1:n_eq
                r == cur_row && continue
                fac = mat[r, col]
                fac == 0 && continue
                for c in 1:(n_var + 1)
                    mat[r, c] = Int(mod(Int128(mat[r, c]) - Int128(fac) * mat[cur_row, c], ell))
                end
            end
            cur_row += 1
            cur_row > n_eq && break
        end

        # Extract k from column 1 (basis index 1 = k).
        pr = pivot_row[1]
        if pr != 0 && mat[pr, 1] == 1
            k_try = mat[pr, n_var + 1]
            if verify_k(k_try)
                k_candidate = k_try
                verbose && @printf("[chain_path] Gaussian elim on constraint system → k=%d ✓\n", k_candidate)
            end
        end

        # If that didn't work, try direct 2×2 pairs on columns (1, b) for b>1.
        if k_candidate === nothing
            for (P1, cm1) in constraints_linear
                k_candidate !== nothing && break
                Q1 = get(cm1, 1, 0)   # coeff of k
                Q1 == 0 && continue
                R1 = get(cm1, 2, 0)   # coeff of L₀
                R1 == 0 || continue   # only handle R=0 case (direct k extraction)
                # Check all other basis elements are 0 too.
                all_zero = all(b == 1 || cv == 0 for (b, cv) in cm1)
                all_zero || continue
                k_try = mod(mod(-P1, ell) * powermod(Q1, ell - 2, ell), ell)
                if verify_k(k_try)
                    k_candidate = k_try
                    verbose && @printf("[chain_path] Direct R=0 constraint → k=%d ✓\n", k_candidate)
                end
            end
        end
    end

    verbose && @printf("[chain_path] assigned=%d/%d, basis=%d, equations=%d, k=%s\n",
                       n_assigned, nF, n_basis, n_eq,
                       k_candidate === nothing ? "nothing" : string(k_candidate))

    return (k                    = k_candidate,
            atom_logs            = nothing,
            chain_path_succeeded = k_candidate !== nothing,
            n_equations          = n_eq)
end
