import Mathlib

/-!
# Genus-2 index calculus: the average-complexity identity (advisory-7, eq 9-10)

`G` stands for the order-ℓ cryptographic subgroup of `J(F_p)` generated by `a`
(ℓ ~ p²). The factor base `F` is a `Finset G`: its elements are the images of
the d1 factor-base curve points, already projected into `G` — their discrete
logs are exactly what index calculus is trying to recover, so we never need a
separate embedding map, `F` just *is* a subset of `G`.

`Δ` here is what advisory-7 §7.3 calls `Δ` directly (an element of `J(F_p)`,
i.e. of `G`), which already absorbs the `Δ ↦ Δ • a` bijection from §2 — eq
(9)-(10) are stated with `Δ` ranging over `J(F_p)` itself, not over `Z/ℓZ`.
-/

open Finset

variable {G : Type*} [AddCommGroup G] [Fintype G] [DecidableEq G]

/-- `N Δ` = number of ordered quadruples `(P1,P2,P3,P4) ∈ F⁴` with
`P1 + P2 - P3 - P4 = Δ`. This is advisory-7's `N(Δ)`. -/
noncomputable def matchCount (F : Finset G) (Δ : G) : ℕ :=
  ((F ×ˢ F ×ˢ F ×ˢ F).filter
    (fun p : G × G × G × G => p.1 + p.2.1 - p.2.2.1 - p.2.2.2 = Δ)).card

/-- Advisory-7, eq (9): summing `N(Δ)` over every `Δ` recovers `B⁴` exactly,
because each of the `B⁴` quadruples contributes to exactly one `Δ`.
This is unconditional — no Sidon property, no additive-energy bound, no
equidistribution assumption anywhere in the proof. -/
theorem sum_matchCount_eq_card_pow_four (F : Finset G) :
    ∑ Δ : G, matchCount F Δ = F.card ^ 4 := by
  have hcard : (F ×ˢ F ×ˢ F ×ˢ F).card = F.card ^ 4 := by
    simp [Finset.card_product, pow_succ, mul_comm]
  have hfiber :
      (F ×ˢ F ×ˢ F ×ˢ F).card =
        ∑ Δ ∈ (Finset.univ : Finset G),
          ((F ×ˢ F ×ˢ F ×ˢ F).filter
            (fun p : G × G × G × G => p.1 + p.2.1 - p.2.2.1 - p.2.2.2 = Δ)).card :=
    Finset.card_eq_sum_card_fiberwise (fun _ _ => Finset.mem_univ _)
  rw [← hcard, hfiber]
  rfl

/-- Advisory-7, eq (10): the mean of `N(Δ)` over a uniformly random
`Δ ∈ G` is *exactly* `B⁴ / |G|`, as a genuine unconditional statement
about the average (not the pointwise / hit-probability statement, which
is the actual open problem in advisory-7 §7.4 onward). -/
theorem average_matchCount_eq (F : Finset G) :
    (∑ Δ : G, (matchCount F Δ : ℚ)) / (Fintype.card G : ℚ)
      = (F.card : ℚ) ^ 4 / (Fintype.card G : ℚ) := by
  have h := sum_matchCount_eq_card_pow_four F
  have hcast : (∑ Δ : G, (matchCount F Δ : ℚ)) = ((F.card ^ 4 : ℕ) : ℚ) := by
    rw [← h]; push_cast; rfl
  rw [hcast]; push_cast; ring
