import Mathlib

/-!
# `Ideal.ofList l ≠ ⊤` from an evaluation witness: general-purpose infrastructure

New this pass. Per `ROADMAP-degree-uniform-step3.md`'s Obligation 1
(`htop_ne_smul`, `AlphaLocusDegreeUniform.lean`'s `decoupledSystem_isRegularSequence`/
`decoupledSystem_zeroDimensional`): showing the 12-generator ideal
`Ideal.ofList (genList ...)` is proper amounts to exhibiting a genuine common
zero of all 12 generators (a real solution to the matching system, which
should exist by construction for an honest DLP instance). Rather than
attempt that curve-specific existence argument directly (it needs an actual
point on each of the two elliptic-curve-style equations `curveA1`/`curveA2`/
`curveB1`/`curveB2` plus the four linear "matching" equations solved for
`U0,U1,V0,V1`, none of which this file assumes anything about), this file
lays down the GENERAL, project-agnostic commutative-algebra fact the
existence argument will need regardless of the curve-specific details: **a
ring hom into ANY nontrivial ring sending every generator in a list to `0`
proves the ideal generated by that list is proper.** This is the single
fact that turns "exhibit a common zero" into "conclude `≠ ⊤`" — pure
`RingHom.ker`/`Ideal.span` algebra, no `Genus2Lean` content, so it belongs
in its own file rather than `DecoupledSystemRegular.lean`/
`AlphaLocusDegreeUniform.lean` (matching this project's `_flat`-first,
prove-generic-lemmas-once discipline, e.g. `MvPolynomialTotalDegreeMulEq.lean`'s
own precedent of factoring out reusable non-project-specific facts).

**What this file does NOT do**: construct the actual curve point or solve
the 4 linear matching equations for `U0,U1,V0,V1` — that's genuine
`Genus2Lean`-specific work (needs `theData`'s `u1_den`/etc. nonvanishing at
a concrete point, which traces back to `Nondegenerate`/`MatrixNondegenerate`-
style conditions) for a future pass, using THIS file's lemmas as the last
step once a concrete evaluation hom and vanishing proof are in hand.

**Not yet REPL-confirmed** — drafted this pass; Claire tests via the REPL.
-/

namespace Genus2Lean

/-- **The headline fact.** If `φ : R →+* S` sends every element of a list
`l` to `0`, and `S` is nontrivial (`0 ≠ 1`), then `Ideal.ofList l ≠ ⊤`. Proof:
`Ideal.ofList l = Ideal.span {r | r ∈ l} ≤ RingHom.ker φ` (`Ideal.span_le`,
since every generator is sent to `0` by hypothesis), and `RingHom.ker φ ≠ ⊤`
because `φ 1 = 1 ≠ 0` (`S` nontrivial) so `1 ∉ RingHom.ker φ`. A subideal of
a proper ideal is proper: spelled out directly via `le_top`/`le_antisymm`
(if `Ideal.ofList l` WERE `⊤`, `hspan` would force `RingHom.ker φ = ⊤` too,
contradicting the previous step) rather than a possibly-differently-named
`ne_top_of_le_ne_top`-style combinator. -/
theorem Ideal.ofList_ne_top_of_forall_eval_eq_zero {R S : Type*} [CommRing R]
    [CommRing S] [Nontrivial S] (φ : R →+* S) (l : List R)
    (hφ : ∀ r ∈ l, φ r = 0) :
    Ideal.ofList l ≠ (⊤ : Ideal R) := by
  -- `Ideal.ofList l` is `@[reducible] abbrev`-defined as `Ideal.span {r | r ∈ l}`
  -- (`Mathlib.RingTheory.Regular.RegularSequence`), so `Ideal.span_le` applies
  -- directly up to reducible defeq -- no explicit `unfold`/`show` needed, `exact`
  -- sees through the abbrev.
  have hspan : Ideal.ofList l ≤ RingHom.ker φ :=
    Ideal.span_le.mpr (fun r hr => RingHom.mem_ker.mpr (hφ r hr))
  have hker_ne_top : RingHom.ker φ ≠ (⊤ : Ideal R) := by
    intro hcontra
    have h1 : (1 : R) ∈ RingHom.ker φ := hcontra ▸ Submodule.mem_top
    have : φ 1 = 0 := RingHom.mem_ker.mp h1
    rw [map_one] at this
    exact one_ne_zero this
  -- `Ideal.ofList l ≤ RingHom.ker φ ≠ ⊤` forces `Ideal.ofList l ≠ ⊤` directly:
  -- if it WERE `⊤`, `hspan` would give `⊤ ≤ RingHom.ker φ`, i.e. `RingHom.ker
  -- φ = ⊤` (`top_le_iff`/`le_antisymm` with `le_top`), contradicting
  -- `hker_ne_top`. Spelled out via basic `PartialOrder`/`OrderTop` API
  -- (`le_top`, `le_antisymm`) rather than a possibly-differently-named
  -- `ne_top_of_le_ne_top` combinator, to avoid guessing a Mathlib name.
  intro hcontra
  apply hker_ne_top
  rw [hcontra] at hspan
  exact le_antisymm le_top hspan

/-- **The `• ⊤` form, matching `htop_ne_smul`'s literal statement.** In
`Ideal (Rdec p)` (i.e. `Submodule (Rdec p) (Rdec p)`), `I • (⊤ : Ideal R) =
I * ⊤ = I` (`Ideal.smul_eq_mul` then `Ideal.mul_top`), so this is
definitionally the same fact as `Ideal.ofList_ne_top_of_forall_eval_eq_zero`
above, just stated in `AlphaLocusDegreeUniform.lean`'s own
`Ideal.ofList l • ⊤ ≠ ⊤` shape so it can be `exact`-applied directly against
`decoupledSystem_isRegularSequence`/`decoupledSystem_zeroDimensional`'s
`htop_ne_smul` hypothesis without an extra rewrite at the call site. -/
theorem Ideal.ofList_smul_top_ne_top_of_forall_eval_eq_zero {R S : Type*}
    [CommRing R] [CommRing S] [Nontrivial S] (φ : R →+* S) (l : List R)
    (hφ : ∀ r ∈ l, φ r = 0) :
    Ideal.ofList l • (⊤ : Ideal R) ≠ (⊤ : Ideal R) := by
  rw [Ideal.smul_eq_mul, Ideal.mul_top]
  exact Ideal.ofList_ne_top_of_forall_eval_eq_zero φ l hφ

/-- **Corollary in the shape an actual point-evaluation argument produces.**
Rather than a bare `∀ r ∈ l, φ r = 0` (which forces the caller to already
have the list-membership form in hand), this takes the common case where
`l` is built as a concrete literal list (`[g1, g2, ..., gn]`, matching
`genList`'s own `FuList ++ FvList ++ [curveA1, ...]` shape) and the
vanishing is proved generator-by-generator via `List.forall_mem_cons`-style
unfolding. Stated generically over `List.all`/`decide`-free membership
rather than committing to a fixed length, so it applies uniformly whether
the eventual proof pattern-matches on `genList`'s 12-element structure
directly or works with the list abstractly. -/
theorem Ideal.ofList_ne_top_of_eval_zero_of_mem {R S : Type*} [CommRing R]
    [CommRing S] [Nontrivial S] (φ : R →+* S) (l : List R)
    (hφ : ∀ i : Fin l.length, φ (l.get i) = 0) :
    Ideal.ofList l ≠ (⊤ : Ideal R) := by
  apply Ideal.ofList_ne_top_of_forall_eval_eq_zero φ l
  intro r hr
  obtain ⟨i, hi⟩ := List.mem_iff_get.mp hr
  rw [← hi]
  exact hφ i

end Genus2Lean
