import Mathlib
import Genus2Lean.DivisorClassGroup

/-!
# The matching equation's solution set depends only on `alpha - alpha'`

Formalizes "Lemma 0" from the ChatGPT consult this session's chat log
records (delivered alongside `MatchingEquationTranslation.lean`'s own
`matching_solutions_translate_by_delta`, but a genuinely separate fact
not previously in this codebase): the matching equation
`[P1]+[P2]-[P3]-[P4] = (alpha-alpha') • a` in `Jacobian H D` depends on
the pair `(alpha, alpha')` ONLY through their difference `delta :=
alpha - alpha'`. Two pairs `(alpha,alpha')` and `(alpha'',alpha''')`
sharing the same `delta` therefore define the literal SAME equation, and
hence the literal same solution set `S_delta` — this is not a
convenience relabeling, it is the same `Prop` on the nose (`ring`-level
equality of the two scalars, transported through `zsmul`).

## Why this matters for the open rigidity question

`ROADMAP-monic-annihilator-degree-uniform.md`'s "CORRECTION, later pass"
section identifies the actual remaining open task as: work out, in a
formalizable form, why fixing `(alpha,alpha')` collapses the
`SampleTarget`-level freedom down to a single 0-dimensional fiber. The
ChatGPT writeup's full argument for `Δ = 0` (see
`MatchingEquationTranslation.lean`'s module docstring and
`OrbitMapConstant.lean`) needs, as one of its ingredients, that a common
shift `(alpha,alpha') ↦ (alpha+beta, alpha'+beta)` produces an algebraic
self-map `G(Δ) : S_delta → S_delta` of the SAME solution set, not a map
between two different sets that merely happen to be isomorphic — this
file supplies exactly that fact, and nothing else. It does not touch
`OrbitMapConstant.lean`'s `PreconnectedSpace`/`DiscreteTopology`
hypotheses, and it does not itself produce a `Δ = 0` conclusion.

## What this file does NOT establish (flagged, not silently assumed)

The ChatGPT writeup's own stated caveat, checked and reproduced here
rather than dropped: if `alpha`/`alpha'` are literal integers and
`alpha • a` is the integer (`zsmul`) action used throughout this
project, then varying `alpha` over `ℤ` only sweeps out the CYCLIC
subgroup of `Jacobian H D` generated by `a` (i.e. `AddSubgroup.zmultiples
a`), not all of `Jacobian H D`. So while this file's
`solution_set_eq_of_sub_eq` shows the solution set is well-defined as a
function of `delta : ℤ` alone, the further claim the full rigidity
argument needs — that `G` can be constructed for an ARBITRARY
`Δ ∈ Jacobian H D`, not just `Δ ∈ AddSubgroup.zmultiples a` — is a
separate fact about the concrete `Reduce`/Mumford-coordinate
construction, not a consequence of anything proved here, and is NOT
addressed by this file. See `OrbitMapConstant.lean`'s own docstring for
the same caveat stated at the point where the full argument actually
needs it.
-/

open HyperellipticPolynomial

namespace Genus2Lean
namespace HyperellipticPolynomialMatching

variable {k : Type*} [Field k] {H : HyperellipticPolynomial k}
variable {D : PrincipalDivisorData H}

/-! ## Lemma 0: the matching equation depends only on `alpha - alpha'` -/

/-- **The matching equation `P1+P2-P3-P4 = (alpha-alpha') • a` is
literally unchanged if `(alpha,alpha')` is replaced by any other pair
`(alpha'',alpha''')` with the same difference.**

Pure `AddCommGroup`/`zsmul` algebra: `(alpha-alpha') • a =
(alpha''-alpha''') • a` follows from `hdelta : alpha - alpha' =
alpha'' - alpha'''` by `congrArg (· • a) hdelta`, so the two equations'
right-hand sides agree on the nose — this is definitional replacement of
equal scalars, not an isomorphism between two different targets. -/
theorem matching_target_eq_of_sub_eq
    (a : Jacobian H D) (alpha alpha' alpha'' alpha''' : ℤ)
    (hdelta : alpha - alpha' = alpha'' - alpha''') :
    (alpha - alpha') • a = (alpha'' - alpha''') • a := by
  rw [hdelta]

/-- **Corollary, stated at the solution-set level.** If `(P1,P2,P3,P4)`
solves the matching equation for `(alpha,alpha')` (i.e.
`P1+P2-P3-P4 = (alpha-alpha') • a`) and `(alpha'',alpha''')` shares the
same difference, then `(P1,P2,P3,P4)` solves the matching equation for
`(alpha'',alpha''')` too — immediate from
`matching_target_eq_of_sub_eq`, but stated in the shape a caller
actually has (a solution of one equation, wanting membership in the
other's solution set) rather than the bare scalar identity. -/
theorem isSolution_of_isSolution_of_sub_eq
    (a : Jacobian H D) (alpha alpha' alpha'' alpha''' : ℤ)
    (P1 P2 P3 P4 : Jacobian H D)
    (hdelta : alpha - alpha' = alpha'' - alpha''')
    (hsol : P1 + P2 - P3 - P4 = (alpha - alpha') • a) :
    P1 + P2 - P3 - P4 = (alpha'' - alpha''') • a := by
  rw [hsol, matching_target_eq_of_sub_eq a alpha alpha' alpha'' alpha''' hdelta]

/-- **The solution set itself, as a `Set` of `Jacobian H D`-tuples, is
literally the same set for any two pairs sharing the same difference.**
This is the `S_delta` statement from the ChatGPT writeup, phrased as
`Set` equality rather than a biconditional membership fact, since the
two directions are exactly `isSolution_of_isSolution_of_sub_eq` applied
with `hdelta` and `hdelta.symm`. -/
theorem solution_set_eq_of_sub_eq
    (a : Jacobian H D) (alpha alpha' alpha'' alpha''' : ℤ)
    (hdelta : alpha - alpha' = alpha'' - alpha''') :
    {P : Jacobian H D × Jacobian H D × Jacobian H D × Jacobian H D |
      P.1 + P.2.1 - P.2.2.1 - P.2.2.2 = (alpha - alpha') • a} =
    {P : Jacobian H D × Jacobian H D × Jacobian H D × Jacobian H D |
      P.1 + P.2.1 - P.2.2.1 - P.2.2.2 = (alpha'' - alpha''') • a} := by
  ext ⟨P1, P2, P3, P4⟩
  simp only [Set.mem_setOf_eq]
  constructor
  · exact isSolution_of_isSolution_of_sub_eq a alpha alpha' alpha'' alpha''' P1 P2 P3 P4 hdelta
  · exact isSolution_of_isSolution_of_sub_eq a alpha'' alpha''' alpha alpha' P1 P2 P3 P4 hdelta.symm

/-! ## The `D`-coordinate gauge symmetry

The writeup's second half: writing `Dcoord := P1 + P2 - alpha • a` (the
auxiliary "sample-side" coordinate `AlphaLocusDegreeUniform.lean`'s
`SampleTargetFromAlpha.reducedClass` already uses, up to sign), a common
shift `(alpha,alpha') ↦ (alpha+beta, alpha'+beta)` moves `Dcoord` by
`-beta • a` while leaving `P1,P2,P3,P4` themselves untouched — the
"gauge symmetry of the auxiliary variable, not a transformation of the
`Pᵢ`" point the writeup makes explicit. Recorded here as one more pure
`AddCommGroup`/`zsmul` fact, distinct from the two theorems above
(those are about the EQUATION; this is about the auxiliary coordinate
built from one side of it). -/

/-- `Dcoord` shifts by `-beta • a` under `alpha ↦ alpha + beta`, for any
fixed `P1 P2 a : Jacobian H D`. Pure `zsmul`/`AddCommGroup` algebra:
`(alpha+beta) • a = alpha • a + beta • a` (`add_zsmul`), so subtracting
the shifted value from `P1+P2` is subtracting `alpha • a` (unshifted)
and then `beta • a` further. -/
theorem dcoord_shift (a P1 P2 : Jacobian H D) (alpha beta : ℤ) :
    P1 + P2 - (alpha + beta) • a = (P1 + P2 - alpha • a) - beta • a := by
  rw [add_zsmul]
  abel

end HyperellipticPolynomialMatching
end Genus2Lean
