import Mathlib

/-!
# Transporting an `Ideal.ofList` `finrank` bound across a variable-set
# equivalence

**Why this file exists.** Closing `GenListFinrankAssembly.lean`'s
`genList_finrank_le` needs a bound proved in `MvPolynomial (Fin 12) K`
(via `idxEquivFin`/`FinSuccPeelChainFinrank.lean`'s peel machinery)
transported back onto the literal `Rdec p ⧸ Ideal.ofList genList`
statement in `MvPolynomial Idx K`. Per a ChatGPT consult (logged in this
project's working chat), the clean route is NOT to chase quotient
representatives or unfold `MvPolynomial`'s definition by hand, but to go
through two already-standard Mathlib bridges: `Ideal.map_ofList` (a ring
hom's image of a generated ideal is the ideal generated by the mapped
generators) and `Ideal.quotientEquiv` (an ideal-respecting ring iso
transports to the quotients), composed once and packaged here as a
single reusable lemma — fully generic over the variable-set equivalence
`e : σ ≃ τ`, no `Idx`/`Rdec p`/`theData` content, so it is available for
any future `MvPolynomial`-reindexing transport this project needs, not
just this one.

**Built from `MvPolynomial.renameEquiv`, Mathlib's own bundled
`K`-algebra equivalence for renaming along a bijection** — re-derived
here as a plain `RingEquiv` (`renameRingEquiv`) rather than reused
directly, since the ideal/quotient machinery below (`Ideal.map`,
`Ideal.quotientEquiv`) wants a `≃+*`, not a `≃ₐ[K]`. Confirmed against
current Mathlib4 source this pass (`Mathlib.Algebra.MvPolynomial.Rename`):
`MvPolynomial.renameEquiv (R) (f : σ ≃ τ) : MvPolynomial σ R ≃ₐ[R]
MvPolynomial τ R`, with `@[simp]` lemmas `MvPolynomial.renameEquiv_apply`
(`renameEquiv R f a = rename f a`) and `MvPolynomial.renameEquiv_symm`
(`(renameEquiv R f).symm = renameEquiv R f.symm`) both present and
current — so `renameRingEquiv` below is just
`(renameEquiv K e).toRingEquiv`, with its action on points and its
`.symm` both following from those two simp lemmas plus
`AlgEquiv.coe_ringEquiv`/`AlgEquiv.toRingEquiv_symm`. This avoids the
deprecated `RingEquiv.ofHomInv`/`ofRingHom` route entirely — no manual
two-sided-inverse proof is needed since `renameEquiv` already packages
one.

**Statement, in words**: if a `finrank` bound holds after renaming a
generator list `gens : List (MvPolynomial σ K)` along `e : σ ≃ τ`, the
same bound already held before renaming. Renaming via a bijection is a
`K`-algebra isomorphism, so it can only ever preserve `Module.finrank`,
never change it — this file makes that precise for the
`Ideal.ofList`-quotient presentation specifically (not just for
`MvPolynomial` itself), since that is the shape every `finrank`
statement in this project's peel-chain Assembly actually takes. -/

namespace Genus2Lean

open MvPolynomial

variable {K : Type*} [Field K] {σ τ : Type*}

/-- **The ring isomorphism underlying renaming along a bijection**, built
as the underlying `RingEquiv` of Mathlib's own `MvPolynomial.renameEquiv`
(see the module docstring for the confirmed-current API this relies on).
-/
noncomputable def renameRingEquiv (e : σ ≃ τ) : MvPolynomial σ K ≃+* MvPolynomial τ K :=
  (MvPolynomial.renameEquiv K e).toRingEquiv

@[simp] theorem renameRingEquiv_apply (e : σ ≃ τ) (p : MvPolynomial σ K) :
    renameRingEquiv (K := K) e p = MvPolynomial.rename e p := by
  show MvPolynomial.renameEquiv K e p = MvPolynomial.rename e p
  rw [MvPolynomial.renameEquiv_apply]

@[simp] theorem renameRingEquiv_symm (e : σ ≃ τ) :
    (renameRingEquiv (K := K) e).symm = renameRingEquiv (K := K) e.symm := by
  apply RingEquiv.ext
  intro p
  show (MvPolynomial.renameEquiv K e).symm p = MvPolynomial.rename e.symm p
  rw [MvPolynomial.renameEquiv_symm, MvPolynomial.renameEquiv_apply]

/-- **The core ideal identity**: `Ideal.map` along `renameRingEquiv e`'s
underlying ring hom sends `Ideal.ofList gens` to
`Ideal.ofList (gens.map (rename e))` — immediate from `Ideal.map_ofList`
plus `renameRingEquiv_apply` to identify the resulting mapped list
pointwise with `gens.map (rename e)`. Stated with `.toRingHom` explicitly
(rather than `renameRingEquiv e`'s bare `RingEquiv` coercion) since that
is the form `Ideal.map_ofList` matches syntactically; callers needing the
`RingEquiv`-coerced form (e.g. `Ideal.quotientEquiv`) bridge across via
the confirmed-current Mathlib4 simp lemma `RingEquiv.coe_toRingHom`
(`⇑f.toRingHom = ⇑f`) at the point of use, since the two `Ideal.map`
applications are instantiated at different `FunLike` types and are not
`rfl` at the outer expression. -/
theorem Ideal.map_renameRingEquiv_ofList (e : σ ≃ τ) (gens : List (MvPolynomial σ K)) :
    Ideal.map ((renameRingEquiv (K := K) e).toRingHom : MvPolynomial σ K →+* MvPolynomial τ K)
      (Ideal.ofList gens) = Ideal.ofList (gens.map (MvPolynomial.rename e)) := by
  rw [Ideal.map_ofList]
  apply congrArg Ideal.ofList
  apply List.map_congr_left
  intro p _
  show renameRingEquiv (K := K) e p = MvPolynomial.rename e p
  exact renameRingEquiv_apply e p

/-- **The quotient-ring isomorphism this transport needs**, packaged as
its own `def` so the `finrank`-bound lemma below doesn't have to
re-derive it: `MvPolynomial σ K ⧸ Ideal.ofList gens` and
`MvPolynomial τ K ⧸ Ideal.ofList (gens.map (rename e))` are isomorphic
as `K`-algebras, via `Ideal.quotientEquiv` applied to `renameRingEquiv e`
and the ideal identity above. -/
noncomputable def renameEquiv_ofList_quotientAlgEquiv (e : σ ≃ τ)
    (gens : List (MvPolynomial σ K)) :
    (MvPolynomial σ K ⧸ Ideal.ofList gens) ≃ₐ[K]
      (MvPolynomial τ K ⧸ Ideal.ofList (gens.map (MvPolynomial.rename e))) := by
  set E := renameRingEquiv (K := K) e with hE_def
  -- `Ideal.quotientEquiv (I) (J) (f) (hIJ : J = Ideal.map f I) : R ⧸ I ≃+* S ⧸ J` —
  -- confirmed-current signature (per this project's own working call sites,
  -- e.g. `DecoupledSystemRegular.lean`); the hypothesis direction is
  -- `J = map f I`, so we need `(Ideal.map_renameRingEquiv_ofList e gens).symm`,
  -- not the identity itself.
  set qE : (MvPolynomial σ K ⧸ Ideal.ofList gens) ≃+*
      (MvPolynomial τ K ⧸ Ideal.ofList (gens.map (MvPolynomial.rename e))) :=
    Ideal.quotientEquiv (Ideal.ofList gens) (Ideal.ofList (gens.map (MvPolynomial.rename e)))
      E (by
        -- Bridge `Ideal.map_renameRingEquiv_ofList`'s `.toRingHom`-coerced form
        -- to the `RingEquiv`-coerced form `Ideal.quotientEquiv` needs. This is
        -- `exact`-able by defeq, not merely `simp`-rewritable: confirmed-current
        -- Mathlib4 source states `Ideal.map f I := Ideal.span (f '' I)`, generic
        -- over any `FunLike F R S`, and depending only on `f`'s underlying
        -- function — `⇑E` and `⇑E.toRingHom` are the same `toFun` for a
        -- `RingEquiv` `E`, so `Ideal.map (↑E) I` and `Ideal.map E.toRingHom I`
        -- are definitionally the same ideal, even though `Ideal.map` is
        -- instantiated at different `F` in the two expressions.
        have hmap := (Ideal.map_renameRingEquiv_ofList e gens).symm
        rw [← hE_def] at hmap
        exact hmap) with hqE_def
  refine AlgEquiv.ofRingEquiv (f := qE) ?_
  intro c
  have hlhs : (algebraMap K (MvPolynomial σ K ⧸ Ideal.ofList gens)) c =
      Ideal.Quotient.mk (Ideal.ofList gens) (algebraMap K (MvPolynomial σ K) c) := by
    rw [IsScalarTower.algebraMap_apply K (MvPolynomial σ K)
      (MvPolynomial σ K ⧸ Ideal.ofList gens)]
    rfl
  rw [hlhs, hqE_def, Ideal.quotientEquiv_mk]
  show Ideal.Quotient.mk (Ideal.ofList (gens.map (MvPolynomial.rename e)))
      (E (algebraMap K (MvPolynomial σ K) c)) =
    algebraMap K (MvPolynomial τ K ⧸ Ideal.ofList (gens.map (MvPolynomial.rename e))) c
  have hEalg : E (algebraMap K (MvPolynomial σ K) c) = algebraMap K (MvPolynomial τ K) c := by
    rw [MvPolynomial.algebraMap_eq, MvPolynomial.algebraMap_eq, renameRingEquiv_apply,
      MvPolynomial.rename_C]
  rw [hEalg]
  have hrhs : (algebraMap K (MvPolynomial τ K ⧸
      Ideal.ofList (gens.map (MvPolynomial.rename e)))) c =
      Ideal.Quotient.mk (Ideal.ofList (gens.map (MvPolynomial.rename e)))
        (algebraMap K (MvPolynomial τ K) c) := by
    rw [IsScalarTower.algebraMap_apply K (MvPolynomial τ K)
      (MvPolynomial τ K ⧸ Ideal.ofList (gens.map (MvPolynomial.rename e)))]
    rfl
  rw [hrhs]

/-- **The reusable transport lemma.** A `finrank` bound proved after
renaming a generator list along a bijection `e : σ ≃ τ` already held
before renaming — since `renameEquiv_ofList_quotientAlgEquiv` is a
`K`-algebra isomorphism, `Module.finrank` agrees on the nose across it
(`LinearEquiv.finrank_eq`). This is the exact bridge
`GenListFinrankAssembly.lean` needs to pull a bound established in
`MvPolynomial (Fin 12) (F p)` (via `idxEquivFin`) back onto
`MvPolynomial Idx (F p) = Rdec p`. -/
theorem finrank_ofList_le_of_finrank_ofList_map_rename_le (e : σ ≃ τ)
    (gens : List (MvPolynomial σ K)) {bound : ℕ}
    (h : Module.finrank K (MvPolynomial τ K ⧸
      Ideal.ofList (gens.map (MvPolynomial.rename e))) ≤ bound) :
    Module.finrank K (MvPolynomial σ K ⧸ Ideal.ofList gens) ≤ bound := by
  rw [LinearEquiv.finrank_eq (renameEquiv_ofList_quotientAlgEquiv e gens).toLinearEquiv]
  exact h

end Genus2Lean
